Repository EmbarkStudios/quilkin, pull requests merged in 2021-07, with the labels that each got.

#331 Fix link to twitter page
  README.md
Labels: cla: yes, kind/cleanup, kind/documentation

#332 Create BRANDING.md
  BRANDING.md
Labels: cla: yes

#333 Update BRANDING.md
  BRANDING.md
Labels: area/meta, cla: yes, kind/cleanup

#336 Add announcements to the README
  README.md
Labels: cla: yes, kind/documentation

#335 Add a companies using Quilkin section
  README.md
  image/embark.png
Labels: cla: yes

#337 Fixed README.md typo: where -> were
  README.md
Labels: cla: yes

#334 Move packet buffer to heap
  src/proxy/server.rs
Labels: cla: yes

#338 Make licence explicit in Cargo.toml
  Cargo.toml
Labels: area/meta, cla: yes, kind/cleanup

#341 Security: Updated tokio + prost-types dependencies
  Cargo.toml
  src/xds.rs
  src/xds/ads_client.rs
  tests/xds.rs
Labels: area/security, cla: yes

#342 Oops, most of the badges didn't have links
  README.md
Labels: cla: yes, kind/cleanup, kind/documentation

#340 Add `cargo-deny` to CI by adding to `make test`
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
Labels: area/build-tools, area/tests, cla: yes, kind/feature

#321 Add naive benchmark
  Cargo.toml
  benches/throughput.rs
  build/README.md
Labels: cla: yes

#348 Documentation snapshot/release README.md section
  README.md
  build/templates/release-issue.md
Labels: cla: yes, kind/cleanup, kind/documentation

#293 Filter Extension Re-organisation
  docs/extensions/filters/writing_custom_filters.md
  examples/quilkin-filter-example/src/main.rs
  macros/src/filter.rs
  macros/src/lib.rs
  src/config.rs
  src/config/config_type.rs
  src/filters.rs
  src/filters/capture_bytes.rs
  src/filters/capture_bytes/capture.rs
  src/filters/capture_bytes/config.rs
  src/filters/capture_bytes/metrics.rs
  src/filters/capture_bytes/proto.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/compress/compressor.rs
  src/filters/compress/config.rs
  src/filters/compress/metrics.rs
  src/filters/compress/proto.rs
  src/filters/concatenate_bytes.rs
  src/filters/concatenate_bytes/config.rs
  src/filters/debug.rs
  src/filters/factory.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/config.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/load_balancer/proto.rs
  src/filters/local_rate_limit.rs
  src/filters/local_rate_limit/metrics.rs
  src/filters/local_rate_limit/proto.rs
  src/filters/metadata.rs
  src/filters/set.rs
  src/filters/token_router.rs
  src/filters/token_router/metrics.rs
  src/filters/token_router/proto.rs
  src/lib.rs
  src/test_utils.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/token_router.rs
Labels: cla: yes
