Repository EmbarkStudios/quilkin, pull requests merged in 2021-09, with the labels that each got.

#381 Hash load balancer
  docs/src/filters/load_balancer.md
  proto/quilkin/extensions/filters/load_balancer/v1alpha1/load_balancer.proto
  src/filters/load_balancer.rs
  src/filters/load_balancer/config.rs
  src/filters/load_balancer/endpoint_chooser.rs
Labels: cla: yes, size/m

#389 Update custom filter example and add CI
  build/Makefile
  examples/quilkin-filter-example/Cargo.toml
  examples/quilkin-filter-example/src/main.rs
Labels: area/tests, kind/cleanup, area/build-tools, cla: yes, size/s

#393 Exit on SIGTERM
  src/runner.rs
Labels: cla: yes, size/s

#391 Use hostname as default proxy id
  Cargo.toml
  docs/src/proxy-configuration.md
  src/config.rs
  src/proxy/server.rs
Labels: cla: yes, size/s

#392 Always backoff and retry management server
  src/xds/ads_client.rs
Labels: cla: yes, size/s

#395 Docs: Updated Custom Filters
  docs/src/filters/writing_custom_filters.md
  examples/quilkin-filter-example/build.rs
  examples/quilkin-filter-example/config.yaml
  examples/quilkin-filter-example/src/greet.proto
  examples/quilkin-filter-example/src/main.rs
Labels: cla: yes, size/l

#396 Add a /config endpoint
  Cargo.toml
  docs/src/admin.md
  docs/src/filters/writing_custom_filters.md
  examples/quilkin-filter-example/src/main.rs
  src/config/config_type.rs
  src/filters.rs
  src/filters/capture_bytes.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/concatenate_bytes.rs
  src/filters/debug.rs
  src/filters/factory.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/manager.rs
  src/filters/registry.rs
  src/filters/token_router.rs
  src/proxy.rs
  src/proxy/admin.rs
  src/proxy/config_dump.rs
  src/proxy/server.rs
  src/test_utils.rs
  src/xds/listener.rs
Labels: cla: yes, size/l

#397 Fix duplicate metric registration for filters
  src/filters/capture_bytes/metrics.rs
  src/filters/compress/metrics.rs
  src/filters/local_rate_limit/metrics.rs
  src/filters/token_router/metrics.rs
  src/metrics.rs
Labels: kind/bug, cla: yes, size/s

#399 Release 0.2.0
  CHANGELOG.md
  Cargo.toml
  README.md
  macros/Cargo.toml
Labels: cla: yes, kind/release, size/s

#402 Preparation for 0.3.0
  Cargo.toml
  build/templates/release-issue.md
  macros/Cargo.toml
Labels: cla: yes, kind/release, size/xs

#400 GitHub: Issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: area/meta, cla: yes, size/s

#406 Add a ttl map and support ratelimiting per IP address
  Cargo.toml
  docs/src/filters.md
  docs/src/filters/local_rate_limit.md
  proto/quilkin/extensions/filters/local_rate_limit/v1alpha1/local_rate_limit.proto
  src/filters/local_rate_limit.rs
  src/filters/set.rs
  src/lib.rs
  src/ttl_map.rs
  tests/local_rate_limit.rs
Labels: cla: yes, kind/breaking, size/xl

#390 Support clear bot history on new build
  build/ci/github-bot/main.go
Labels: cla: yes, size/s
