Repository EmbarkStudios/quilkin, pull requests merged in 2021-11, with the labels that each got.

#419 Replace `SocketAddr` with `EndpointAddress`
  src/endpoint.rs
  src/endpoint/address.rs
  src/filters/chain.rs
  src/filters/debug.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/local_rate_limit.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/write.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/proxy/server.rs
  src/proxy/sessions/error.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
  src/test_utils.rs
  src/ttl_map.rs
  src/xds.rs
  src/xds/cluster.rs
  src/xds/error.rs
  src/xds/listener.rs
  tests/concatenate_bytes.rs
  tests/filters.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/xds.rs
Labels: kind/design, cla: yes, size/xl

#430 Refactor AdsClient and switch backoff with tryhard
  Cargo.toml
  src/filters/manager.rs
  src/proxy/server/resource_manager.rs
  src/xds/ads_client.rs
  src/xds/cluster.rs
Labels: kind/cleanup, cla: yes, size/l

#431 Fixes for filter documentation
  docs/src/SUMMARY.md
  docs/src/filters.md
Labels: kind/bug, kind/documentation, cla: yes, size/s

#432 Documentation for Firewall filter
  docs/src/SUMMARY.md
  docs/src/filters.md
  docs/src/filters/firewall.md
  src/filters/firewall.rs
  src/lib.rs
Labels: kind/documentation, kind/feature, cla: yes, size/m

#434 Add "Rust Doc" link to each Filter
  docs/src/filters/capture_bytes.md
  docs/src/filters/compress.md
  docs/src/filters/concatenate_bytes.md
  docs/src/filters/debug.md
  docs/src/filters/load_balancer.md
  docs/src/filters/local_rate_limit.md
  docs/src/filters/token_router.md
Labels: kind/documentation, kind/feature, cla: yes, size/s

#360 XDS Management Server
  .gitignore
  cloudbuild.yaml
  examples/xds-management-server/README.md
  examples/xds-management-server/ci/.golangci.yaml
  examples/xds-management-server/cmd/controller.go
  examples/xds-management-server/cmd/file/file.go
  examples/xds-management-server/go.mod
  examples/xds-management-server/go.sum
  examples/xds-management-server/pkg/cluster/agones/agones.go
  examples/xds-management-server/pkg/cluster/agones/agones_test.go
  examples/xds-management-server/pkg/cluster/cluster.go
  examples/xds-management-server/pkg/filterchain/filterchain.go
  examples/xds-management-server/pkg/filterchain/k8s/k8s.go
  examples/xds-management-server/pkg/filterchain/k8s/k8s_test.go
  examples/xds-management-server/pkg/filters/capture_bytes/v1alpha1/capture_bytes.pb.go
  examples/xds-management-server/pkg/filters/compress/v1alpha1/compress.pb.go
  examples/xds-management-server/pkg/filters/concatenate_bytes/v1alpha1/concatenate_bytes.pb.go
  examples/xds-management-server/pkg/filters/debug/v1alpha1/debug.pb.go
  examples/xds-management-server/pkg/filters/filters.go
  examples/xds-management-server/pkg/filters/load_balancer/v1alpha1/load_balancer.pb.go
  examples/xds-management-server/pkg/filters/local_rate_limit/v1alpha1/local_rate_limit.pb.go
  examples/xds-management-server/pkg/k8s/k8s.go
  examples/xds-management-server/pkg/providers/file.go
  examples/xds-management-server/pkg/providers/file_test.go
  examples/xds-management-server/pkg/resources/resources.go
  examples/xds-management-server/pkg/resources/resources_test.go
  examples/xds-management-server/pkg/server/callbacks.go
  examples/xds-management-server/pkg/server/server.go
  examples/xds-management-server/pkg/snapshot/snapshot.go
  examples/xds-management-server/pkg/snapshot/snapshot_test.go
  examples/xds-management-server/pkg/testing/controller.go
Labels: kind/feature, area/examples, cla: yes, size/xl

#385 replace slog with tracing in Filter
  Cargo.toml
  src/config.rs
  src/config/config_type.rs
  src/endpoint.rs
  src/filters/capture_bytes.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/debug.rs
  src/filters/firewall.rs
  src/filters/local_rate_limit.rs
  src/filters/registry.rs
  src/filters/set.rs
  src/filters/token_router.rs
  src/main.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/proxy/server.rs
  src/runner.rs
  src/test_utils.rs
  src/ttl_map.rs
  src/xds/listener.rs
  tests/compress.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/local_rate_limit.rs
  tests/token_router.rs
Labels: cla: yes, size/l

#435 Move xds-management-server to the top-level
  .gitignore
  cloudbuild.yaml
  examples/xds-management-server/ci/.golangci.yaml
  xds/README.md
  xds/ci/.golangci.yaml
  xds/cmd/controller.go
  xds/cmd/file/file.go
  xds/go.mod
  xds/go.sum
  xds/pkg/cluster/agones/agones.go
  xds/pkg/cluster/agones/agones_test.go
  xds/pkg/cluster/cluster.go
  xds/pkg/filterchain/filterchain.go
  xds/pkg/filterchain/k8s/k8s.go
  xds/pkg/filterchain/k8s/k8s_test.go
  xds/pkg/filters/capture_bytes/v1alpha1/capture_bytes.pb.go
  xds/pkg/filters/compress/v1alpha1/compress.pb.go
  xds/pkg/filters/concatenate_bytes/v1alpha1/concatenate_bytes.pb.go
  xds/pkg/filters/debug/v1alpha1/debug.pb.go
  xds/pkg/filters/filters.go
  xds/pkg/filters/load_balancer/v1alpha1/load_balancer.pb.go
  xds/pkg/filters/local_rate_limit/v1alpha1/local_rate_limit.pb.go
  xds/pkg/k8s/k8s.go
  xds/pkg/providers/file.go
  xds/pkg/providers/file_test.go
  xds/pkg/resources/resources.go
  xds/pkg/resources/resources_test.go
  xds/pkg/server/callbacks.go
  xds/pkg/server/server.go
  xds/pkg/snapshot/snapshot.go
  xds/pkg/snapshot/snapshot_test.go
  xds/pkg/testing/controller.go
Labels: cla: yes, size/s

#438 Save iperf3 metrics.json in /quilkin
  examples/iperf3/run.sh
Labels: kind/bug, area/examples, area/performance, cla: yes, size/xs

#440 Align Filter Chain metrics with conventions
  docs/src/filters.md
  src/filters/chain.rs
Labels: area/operations, kind/cleanup, cla: yes, size/s

#436 Add `metadata::Value`
  docs/src/filters.md
  src/filters/capture_bytes.rs
  src/filters/chain.rs
  src/filters/read.rs
  src/filters/token_router.rs
  src/filters/write.rs
  src/metadata.rs
  src/test_utils.rs
Labels: cla: yes, kind/breaking, size/m

#439 Upgrade Tokio for RUSTSEC-2021-0124
  Cargo.toml
  examples/quilkin-filter-example/Cargo.toml
Labels: area/security, cla: yes, size/s

#442 Fix bug archiving dependencies
  image/archive_dependencies.sh
Labels: kind/bug, area/build-tools, cla: yes, size/xs

#445 Docs: Fix broken links
  docs/src/faq.md
  docs/src/filters.md
  docs/src/filters/capture_bytes.md
  docs/src/filters/compress.md
  docs/src/filters/token_router.md
  docs/src/proxy.md
  docs/src/quickstart-agones-xonotic.md
  docs/src/using.md
  src/metadata.rs
Labels: kind/bug, kind/documentation, cla: yes, size/s

#446 xds-server: Create informers before starting informer factory
  xds/cmd/controller.go
Labels: cla: yes, size/s

#437 xds-server updates
  xds/README.md
  xds/ci/.golangci.yaml
  xds/ci/Dockerfile
  xds/cmd/controller.go
  xds/cmd/file/file.go
  xds/go.mod
  xds/go.sum
  xds/pkg/cluster/agones/agones.go
  xds/pkg/cluster/agones/agones_test.go
  xds/pkg/filterchain/k8s/k8s.go
  xds/pkg/filterchain/k8s/k8s_test.go
  xds/pkg/filters/filters.go
  xds/pkg/filters/token_router/v1alpha1/token_router.pb.go
  xds/pkg/metrics/metrics.go
  xds/pkg/resources/resources.go
  xds/pkg/resources/resources_test.go
  xds/pkg/server/callbacks.go
  xds/pkg/server/server.go
  xds/pkg/snapshot/snapshot.go
Labels: cla: yes, size/l
