Repository EmbarkStudios/quilkin, pull requests merged in 2021-12, with the labels that each got.

#449 CI: Documentation test gen, links, images, etc.
  build/Makefile
  build/build-image/Dockerfile
  cloudbuild.yaml
  docs/htmltest.yaml
Labels: kind/feature, area/tests, cla: yes, size/s

#441 Metric: Total Packet processing time
  docs/src/proxy.md
  src/filters/chain.rs
  src/filters/firewall/metrics.rs
  src/metrics.rs
  src/proxy/server.rs
  src/proxy/server/metrics.rs
  src/proxy/sessions.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
Labels: kind/feature, cla: yes, size/m

#451 Fix licence field in macros Cargo.toml
  macros/Cargo.toml
Labels: kind/cleanup, cla: yes, size/xs

#452 Example Grafana Graph for Packet Processing Times
  examples/grafana-dashboards/README.md
  examples/grafana-dashboards/dashboards/dashboard-gameservers.yaml
  examples/grafana-dashboards/quilkin-general.png
Labels: cla: yes, size/m

#455 Update to Rust 1.57
  rust-toolchain.toml
  src/filters/factory.rs
Labels: kind/cleanup, size/xs
