Repository EmbarkStudios/quilkin, pull requests merged in 2021-08, with the labels that each got.

#351 Update to Rust 1.54.0
  rust-toolchain.toml
  src/filters/chain.rs
  src/lib.rs
  src/proxy/server.rs
  src/proxy/sessions/session.rs
  src/xds.rs
  src/xds/cluster.rs
  tests/xds.rs
Labels: cla: yes

#352 Remove need for nightly in CI and developer guide
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
Labels: kind/cleanup, area/build-tools, cla: yes

#350 Move I/O and configuration out of runner::run
  examples/quilkin-filter-example/src/main.rs
  src/config.rs
  src/config/builder.rs
  src/main.rs
  src/runner.rs
Labels: cla: yes

#308 Cleanup other parts of the public API.
  benches/throughput.rs
  docs/extensions/filters/capture_bytes.md
  docs/extensions/filters/compress.md
  docs/extensions/filters/concatenate_bytes.md
  docs/extensions/filters/debug.md
  docs/extensions/filters/filters.md
  docs/extensions/filters/load_balancer.md
  docs/extensions/filters/local_rate_limit.md
  docs/extensions/filters/token_router.md
  docs/extensions/filters/writing_custom_filters.md
  src/config.rs
  src/lib.rs
  src/main.rs
  src/proxy/builder.rs
  tests/filters.rs
  tests/health.rs
  tests/metrics.rs
  tests/xds.rs
Labels: cla: yes

#353 GH Action: Sizing labels on PRs
  .github/workflows/labeler.yml
  .gitignore
Labels: kind/feature, area/build-tools, cla: yes

#354 Remove initial xds update delay
  docs/using.md
  src/cluster/cluster_manager.rs
  src/filters/manager.rs
  src/proxy/server/resource_manager.rs
Labels: cla: yes, size/m

#319 Add mdbook and GitHub pages deployment
  .github/workflows/docs.yml
  .gitignore
  docs/book.toml
  docs/src/SUMMARY.md
  docs/src/admin.md
  docs/src/faq.md
  docs/src/filters.md
  docs/src/filters/capture_bytes.md
  docs/src/filters/compress.md
  docs/src/filters/concatenate_bytes.md
  docs/src/filters/debug.md
  docs/src/filters/load_balancer.md
  docs/src/filters/local_rate_limit.md
  docs/src/filters/token_router.md
  docs/src/filters/writing_custom_filters.md
  docs/src/integrations.md
  docs/src/introduction.md
  docs/src/proxy-configuration.md
  docs/src/proxy.md
  docs/src/quickstart-agones-xonotic.md
  docs/src/quickstart-netcat.md
  docs/src/session.md
  docs/src/using.md
  docs/src/xds.md
  src/lib.rs
Labels: cla: yes, size/m

#355 Fix for change: --filename to --config
  docs/src/filters/writing_custom_filters.md
  docs/src/proxy-configuration.md
  docs/src/quickstart-agones-xonotic.md
  docs/src/quickstart-netcat.md
  examples/agones-xonotic/README.md
  image/Dockerfile
Labels: kind/bug, kind/documentation, area/build-tools, cla: yes, size/s

#356 Fix README.md development documentation links
  README.md
Labels: kind/documentation, kind/cleanup, cla: yes, size/s

#357 Remove redundant cfg(test)
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/token_router.rs
  tests/xds.rs
Labels: kind/cleanup, cla: yes, size/xl

#361 Better language on using.md
  docs/src/using.md
Labels: kind/documentation, kind/cleanup, cla: yes

#362 Add "examples" page to the documentation.
  docs/src/SUMMARY.md
  docs/src/examples.md
Labels: kind/documentation, kind/feature, cla: yes

#359 Include endpoint token and metadata from cluster update
  src/cluster/cluster_manager.rs
Labels: kind/bug, cla: yes, size/m

#364 Add a type for session keys
  src/proxy.rs
  src/proxy/server.rs
  src/proxy/sessions.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
Labels: cla: yes, size/s

#366 `make docs` to preview documentation locally
  build/Makefile
  build/build-image/Dockerfile
Labels: kind/feature, area/build-tools, cla: yes, size/s

#358 Refactor Endpoint and Metadata from cluster and config into one type.
  benches/throughput.rs
  src/cluster.rs
  src/cluster/cluster_manager.rs
  src/config.rs
  src/config/builder.rs
  src/config/metadata.rs
  src/endpoint.rs
  src/extensions/filter_registry.rs
  src/filters/capture_bytes.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/extensions/concatenate_bytes.rs
  src/filters/extensions/load_balancer.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/local_rate_limit.rs
  src/filters/manager.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/token_router.rs
  src/filters/write.rs
  src/lib.rs
  src/metadata.rs
  src/prost.rs
  src/proxy/builder.rs
  src/proxy/server.rs
  src/proxy/server/resource_manager.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
  src/test_utils.rs
  src/xds.rs
  src/xds/cluster.rs
  src/xds/error.rs
  src/xds/listener.rs
  src/xds/metadata.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/token_router.rs
Labels: cla: yes, size/xl

#368 Delete filter_registry.rs
  src/extensions/filter_registry.rs
Labels: cla: yes, size/m

#363 Update doc links
  docs/src/filters.md
  docs/src/filters/capture_bytes.md
  docs/src/filters/writing_custom_filters.md
  docs/src/integrations.md
  docs/src/xds.md
Labels: cla: yes, size/s

#370 CI: Add cross compile and basic image test
  build/Makefile
  cloudbuild.yaml
Labels: kind/feature, area/build-tools, cla: yes, size/s

#388 Add github CODEOWNERS file
  CODEOWNERS
Labels: cla: yes, size/xs

#386 Remove test subcommand from clap for 0.2
  src/main.rs
Labels: cla: yes, size/xs
