Repository EmbarkStudios/quilkin, pull requests merged in 2022-12, with the labels that each got.

#654 Make: Move cargo registry to /target/build-image/
  build/Makefile
Labels: kind/cleanup, area/build-tools, size/xs

#658 Move instrument level to trace
  src/proxy.rs
Labels: size/xs

#659 Add retry for provider task
  src/cli/manage.rs
Labels: size/s

#661 Rename run command to proxy
  agones/src/pod.rs
  agones/src/sidecar.rs
  agones/src/xds.rs
  cloudbuild.yaml
  docs/src/admin.md
  docs/src/file-configuration.md
  docs/src/proxy-mode.md
  docs/src/proxy/maxmind.md
  docs/src/quickstarts/netcat.md
  docs/src/xds.md
  examples/agones-xonotic-sidecar/sidecar-compress.yaml
  examples/agones-xonotic-sidecar/sidecar.yaml
  examples/agones-xonotic-xds/README.md
  examples/agones-xonotic-xds/proxy-pool.yaml
  examples/iperf3/run.sh
  src/cli.rs
  src/cli/proxy.rs
Labels: kind/cleanup, kind/breaking, size/s

#665 Error for invalid endpoint
  src/xds/client.rs
Labels: kind/cleanup, size/s

#668 --version flag for binary
  Cargo.toml
  src/cli.rs
Labels: kind/feature, area/user-experience, size/s

#667 Agones xDS Provider Quickstart
  docs/src/SUMMARY.md
  docs/src/faq.md
  docs/src/quickstarts/_agones.md
  docs/src/quickstarts/agones-xonotic-sidecar.md
  docs/src/quickstarts/agones-xonotic-xds.md
  docs/src/quickstarts/netcat.md
  docs/src/quickstarts/xonotic-address.png
Labels: kind/documentation, kind/feature, size/m
