Repository EmbarkStudios/quilkin, pull requests merged in 2022-11, with the labels that each got.

#638 Implement string interning and symbol resolution for metadata keys
  Cargo.toml
  src/filters/capture.rs
  src/filters/capture/config.rs
  src/filters/chain.rs
  src/filters/match.rs
  src/filters/match/config.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/metadata.rs
  src/metadata/symbol.rs
  src/test_utils.rs
Labels: size/m

#640 Update to Rust 1.65.0
  rust-toolchain.toml
  src/filters/token_router.rs
  src/metadata/symbol.rs
  src/metrics.rs
  src/proxy/sessions/metrics.rs
Labels: kind/cleanup, area/build-tools, size/s

#641 Consistency of "packets_dropped_total" metric
  docs/src/filters/capture.md
  docs/src/filters/local_rate_limit.md
  docs/src/filters/token_router.md
  examples/grafana-dashboards/dashboards/dashboard-gameservers.yaml
  src/filters/capture/metrics.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/compress/metrics.rs
  src/filters/local_rate_limit/metrics.rs
  src/filters/token_router.rs
  src/filters/token_router/metrics.rs
  src/metrics.rs
  src/proxy.rs
  src/proxy/sessions.rs
Labels: area/operations, kind/cleanup, size/m

#645 Total review of guide
  docs/htmltest.yaml
  docs/preprocessor.sh
  docs/src/SUMMARY.md
  docs/src/admin.md
  docs/src/faq.md
  docs/src/filters.md
  docs/src/integrations.md
  docs/src/introduction.md
  docs/src/proxy-mode.md
  docs/src/proxy.md
  docs/src/proxy/concepts.md
  docs/src/proxy/filters/capture.md
  docs/src/proxy/filters/compress.md
  docs/src/proxy/filters/concatenate_bytes.md
  docs/src/proxy/filters/debug.md
  docs/src/proxy/filters/drop.md
  docs/src/proxy/filters/firewall.md
  docs/src/proxy/filters/load_balancer.md
  docs/src/proxy/filters/local_rate_limit.md
  docs/src/proxy/filters/match.md
  docs/src/proxy/filters/pass.md
  docs/src/proxy/filters/timestamp.md
  docs/src/proxy/filters/token_router.md
  docs/src/proxy/filters/writing_custom_filters.md
  docs/src/proxy/maxmind.md
  docs/src/proxy/metrics.md
  docs/src/quickstart.md
  docs/src/quickstarts/agones-xonotic.md
  docs/src/quickstarts/netcat.md
  docs/src/sdks.md
  docs/src/session.md
  docs/src/using.md
  docs/src/xds.md
  docs/src/xds/builtin.md
  docs/src/xds/metrics.md
  docs/src/xds/providers/agones.md
  docs/src/xds/providers/filesystem.md
  examples/agones-xonotic-xds/xds-control-plane.yaml
  src/lib.rs
Labels: size/xl

#646 Update release instructions to remove `-debug`
  build/release/README.md
Labels: kind/documentation, kind/cleanup, kind/release, size/s

#648 Release 0.4.0
  CHANGELOG.md
  Cargo.toml
  README.md
  build/templates/release-issue.md
  docs/src/quickstarts/agones-xonotic.md
  macros/Cargo.toml
Labels: kind/release, size/m

#649 Bump version to 0.5.0-dev
  Cargo.toml
  macros/Cargo.toml
Labels: size/xs

#652 docs/src/proxy/filters/writing_custom_filters: fix port typo
  docs/src/proxy/filters/writing_custom_filters.md
Labels: size/xs

#650 Remove map_proto_enum and simplify proto enum conversions
  src/filters/compress.rs
  src/filters/compress/config.rs
  src/filters/concatenate_bytes/config.rs
  src/filters/error.rs
  src/filters/firewall/config.rs
  src/filters/load_balancer/config.rs
Labels: size/m

#653 Fix for #651 vendor-protoc feature
  Cargo.toml
  agones/Cargo.toml
  build.rs
  build/Makefile
  build/darwin-builder/setup.sh
Labels: size/s

#651 Update dependencies
  Cargo.toml
  agones/Cargo.toml
  build.rs
  build/Makefile
  build/darwin-builder/setup.sh
  examples/quilkin-filter-example/Cargo.toml
  examples/quilkin-filter-example/build.rs
Labels: size/m
