Repository EmbarkStudios/quilkin, pull requests merged in 2022-08, with the labels that each got.

#554 Use base64 when logging token, add fmt::Display impl for metadata::Value
  src/config/watch/agones/crd.rs
  src/filters/capture.rs
  src/filters/match.rs
  src/filters/token_router.rs
  src/metadata.rs
Labels: size/s

#557 Fix security advisory in chrono
  Cargo.toml
Labels: area/security, size/xs

#562 Use status.ports rather spec.ports with Agones
  src/config/watch/agones/crd.rs
Labels: size/xs

#563 Clarify packet direction in traces, use base64 for bytes_to_string
  src/proxy/server.rs
  src/proxy/sessions/session.rs
  src/utils/debug.rs
Labels: kind/cleanup, size/s

#561 Improve build-image incremental workflow
  .dockerignore
  build/Makefile
  cloudbuild.yaml
  image/Dockerfile
Labels: kind/feature, area/build-tools, size/s

#566 Recover xDS connection if stream terminates
  Cargo.toml
  src/xds.rs
  src/xds/client.rs
Labels: size/m

#567 Catch tonic errors in xDS client loop
  src/xds.rs
  src/xds/client.rs
Labels: size/s

#560 Only search for config file when required
  src/main.rs
Labels: kind/bug, size/s

#565 Add BUILD_LOCAL to build tools
  .dockerignore
  build/Makefile
  build/README.md
  image/Dockerfile
Labels: size/s

#569 Extend `fs::write` test delay, and remove admin server from test to prevent flakiness
  src/config/watch/fs.rs
  src/xds.rs
Labels: size/xs

#571 Resubscribe to resources after disconnect, fix test flakiness
  Cargo.toml
  src/config/watch/fs.rs
  src/xds.rs
  src/xds/client.rs
Labels: size/s

#570 Refactor CLI organisation, and improve termination
  docs/src/filters/writing_custom_filters.md
  examples/quilkin-filter-example/Cargo.toml
  examples/quilkin-filter-example/src/main.rs
  src/cli.rs
  src/cli/generate_config_schema.rs
  src/cli/manage.rs
  src/cli/run.rs
  src/lib.rs
  src/main.rs
  src/runner.rs
  src/xds.rs
  src/xds/server.rs
Labels: size/l

#568 Update to Rust 1.63.0
  examples/quilkin-filter-example/src/main.rs
  macros/src/include.rs
  rust-toolchain.toml
  src/config.rs
  src/config/config_type.rs
  src/config/error.rs
  src/filters/capture/affix.rs
  src/filters/compress/config.rs
  src/filters/concatenate_bytes/config.rs
  src/filters/error.rs
  src/filters/firewall/config.rs
  src/filters/load_balancer/config.rs
  src/filters/local_rate_limit.rs
  src/filters/match/config.rs
  src/filters/token_router.rs
  src/xds/server.rs
Labels: size/s

#576 Update configuration reference docs
  docs/src/proxy-configuration.md
Labels: kind/documentation, kind/cleanup, size/s

#577 Update example configurations to new format
  examples/agones-xonotic/client-compress.yaml
  examples/agones-xonotic/sidecar-compress.yaml
  examples/agones-xonotic/sidecar.yaml
  examples/control-plane.yaml
  examples/iperf3/Dockerfile
  examples/iperf3/proxy.yaml
  examples/proxy.yaml
Labels: area/examples, kind/cleanup, size/s

#578 Move proxy::Server to Proxy and sessions::session to sessions
  benches/throughput.rs
  docs/src/filters.md
  docs/src/filters/capture.md
  docs/src/filters/compress.md
  docs/src/filters/concatenate_bytes.md
  docs/src/filters/debug.md
  docs/src/filters/firewall.md
  docs/src/filters/load_balancer.md
  docs/src/filters/local_rate_limit.md
  docs/src/filters/match.md
  docs/src/filters/token_router.md
  docs/src/filters/writing_custom_filters.md
  examples/quilkin-filter-example/src/main.rs
  src/cli/run.rs
  src/lib.rs
  src/proxy.rs
  src/proxy/server.rs
  src/proxy/sessions.rs
  src/proxy/sessions/manager.rs
  src/proxy/sessions/session.rs
  src/test_utils.rs
  src/xds.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/token_router.rs
Labels: size/xl

#581 Relax trait bounds for Default, Deserialize, and Serialize for Slot<T>
  src/config/slot.rs
Labels: size/s

#580 Basic Agones GameServer integration test
  agones/src/lib.rs
  agones/src/sidecar.rs
  src/config/watch.rs
  src/config/watch/agones.rs
  src/config/watch/agones/crd.rs
Labels: kind/feature, area/tests, size/m

#582 Agones GameServer + Quilkin sidecar test
  agones/src/lib.rs
  agones/src/pod.rs
  agones/src/sidecar.rs
  build/Makefile
Labels: kind/feature, area/tests, size/m
