Repository EmbarkStudios/quilkin, pull requests merged in 2022-03, with the labels that each got.

#500 Release 0.3.0
  CHANGELOG.md
  Cargo.toml
  README.md
  macros/Cargo.toml
Labels: size/m

#487 Add `Debug` for `FilterChain` and `FilterManager::with_dynamic`
  src/config/builder.rs
  src/filters/chain.rs
Labels: size/s

#489 Refactor FilterRegistry into private static
  Cargo.toml
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/debug.rs
  src/filters/factory.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/manager.rs
  src/filters/match.rs
  src/filters/registry.rs
  src/filters/set.rs
  src/filters/token_router.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/proxy/server.rs
  src/proxy/server/resource_manager.rs
  src/runner.rs
  src/test_utils.rs
  src/xds/ads_client.rs
  src/xds/listener.rs
  tests/filters.rs
Labels: size/m

#490 Refactor Metrics Registry into public static
  src/cluster/cluster_manager.rs
  src/cluster/metrics.rs
  src/filters/capture.rs
  src/filters/capture/metrics.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/compress/metrics.rs
  src/filters/debug.rs
  src/filters/factory.rs
  src/filters/firewall.rs
  src/filters/firewall/metrics.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/local_rate_limit/metrics.rs
  src/filters/manager.rs
  src/filters/match.rs
  src/filters/registry.rs
  src/filters/token_router.rs
  src/filters/token_router/metrics.rs
  src/metrics.rs
  src/proxy.rs
  src/proxy/admin.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/proxy/metrics.rs
  src/proxy/server.rs
  src/proxy/server/metrics.rs
  src/proxy/server/resource_manager.rs
  src/proxy/sessions/metrics.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
  src/test_utils.rs
  src/xds/ads_client.rs
  src/xds/listener.rs
  src/xds/metrics.rs
  tests/metrics.rs
Labels: kind/cleanup, size/l

#491 Refactor FilterManager into SharedFilterChain
  src/filters.rs
  src/filters/chain.rs
  src/filters/chain/shared.rs
  src/filters/manager.rs
  src/filters/match.rs
  src/proxy/admin.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/proxy/server.rs
  src/proxy/server/resource_manager.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
  src/test_utils.rs
  src/xds/ads_client.rs
  src/xds/listener.rs
Labels: size/l

#493 Refactor ClusterManager into SharedCluster
  src/cluster.rs
  src/cluster/cluster_manager.rs
  src/cluster/shared.rs
  src/endpoint.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/chain/shared.rs
  src/filters/compress.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/registry.rs
  src/filters/token_router.rs
  src/proxy/admin.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/proxy/server.rs
  src/proxy/server/resource_manager.rs
  src/test_utils.rs
  src/xds.rs
  src/xds/ads_client.rs
  src/xds/cluster.rs
  src/xds/listener.rs
Labels: size/xl

#504 Multiple documentation fixes
  docs/book.toml
  docs/preprocessor.sh
  docs/src/filters.md
  docs/src/filters/match.md
  src/filters/match.rs
  src/filters/match/config.rs
  src/lib.rs
Labels: size/s

#508 Backporting formatting issues and missed links.
  v0.3.0/book/404.html
  v0.3.0/book/admin.html
  v0.3.0/book/examples.html
  v0.3.0/book/faq.html
  v0.3.0/book/filters.html
  v0.3.0/book/filters/capture.html
  v0.3.0/book/filters/compress.html
  v0.3.0/book/filters/concatenate_bytes.html
  v0.3.0/book/filters/debug.html
  v0.3.0/book/filters/drop.html
  v0.3.0/book/filters/firewall.html
  v0.3.0/book/filters/load_balancer.html
  v0.3.0/book/filters/local_rate_limit.html
  v0.3.0/book/filters/match.html
  v0.3.0/book/filters/pass.html
  v0.3.0/book/filters/token_router.html
  v0.3.0/book/filters/writing_custom_filters.html
  v0.3.0/book/index.html
  v0.3.0/book/integrations.html
  v0.3.0/book/introduction.html
  v0.3.0/book/print.html
  v0.3.0/book/proxy-configuration.html
  v0.3.0/book/proxy.html
  v0.3.0/book/quickstart-agones-xonotic.html
  v0.3.0/book/quickstart-netcat.html
  v0.3.0/book/searchindex.js
  v0.3.0/book/searchindex.json
  v0.3.0/book/session.html
  v0.3.0/book/using.html
  v0.3.0/book/xds.html
Labels: kind/bug, kind/documentation
