Repository EmbarkStudios/quilkin, pull requests merged in 2022-09, with the labels that each got.

#587 Agones + Quilkin xDS integration test.
  agones/Cargo.toml
  agones/src/lib.rs
  agones/src/pod.rs
  agones/src/sidecar.rs
  agones/src/xds.rs
  src/config/watch/agones/crd.rs
Labels: kind/feature, area/tests, size/l

#591 Add ready probe endpoint
  src/admin.rs
  src/admin/health.rs
  src/proxy.rs
Labels: size/s

#592 Add LocalitySet type to ensure there aren't duplicate locality entries
  src/cluster.rs
  src/config/watch/agones.rs
  src/config/watch/fs.rs
  src/xds.rs
Labels: size/m

#594 Remove allocated check for deleted gameserver events
  src/config/watch/agones.rs
Labels: size/xs

#595 Fix metric names in dashboard
  docs/src/proxy.md
  examples/grafana-dashboards/dashboards/dashboard-gameservers.yaml
Labels: size/s

#596 Fix metrics namespace not always being present
  src/metrics.rs
Labels: size/xs

#598 Allow gameservers to not have port
  src/config/watch/agones/crd.rs
Labels: size/xs

#599 Add Build Images to CI results
  build/ci/github-bot/go.mod
  build/ci/github-bot/go.sum
  build/ci/github-bot/main.go
  cloudbuild.yaml
Labels: size/s

#601 Fixes for CI failure on `quilkin run #574`
  cloudbuild.yaml
  docs/src/using.md
  src/cli.rs
  src/config.rs
  src/config/slot.rs
Labels: kind/cleanup, size/s

#574 Add arguments to `quilkin run`
  cloudbuild.yaml
  docs/src/quickstart-netcat.md
  docs/src/using.md
  src/cli.rs
  src/cli/generate_config_schema.rs
  src/cli/manage.rs
  src/cli/run.rs
  src/config.rs
  src/config/slot.rs
  src/endpoint/locality.rs
  src/lib.rs
  src/proxy.rs
Labels: size/m

#602 Docs, tests and bug fixes for /ready
  agones/src/lib.rs
  agones/src/pod.rs
  agones/src/xds.rs
  docs/src/admin.md
  src/admin.rs
  src/proxy.rs
  src/xds/server.rs
Labels: kind/bug, kind/documentation, area/tests, size/m

#603 Add short poll to xDS clients as workaround, improve xDS tracing
  Cargo.toml
  src/config.rs
  src/config/watch/agones.rs
  src/proxy.rs
  src/xds/server.rs
Labels: size/s

#606 remove unwrap
  src/proxy.rs
Labels: size/xs

#607 Docker image entrypoint is now `/quilkin`
  agones/src/lib.rs
  agones/src/pod.rs
  agones/src/sidecar.rs
  agones/src/xds.rs
  cloudbuild.yaml
  docs/src/using.md
  examples/agones-xonotic/README.md
  examples/agones-xonotic/sidecar-compress.yaml
  examples/agones-xonotic/sidecar.yaml
  image/Dockerfile
  image/quilkin.yaml
Labels: kind/feature, area/operations, size/m

#612 (Mostly) Build tools working on arm64
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
Labels: kind/feature, area/build-tools, size/s

#613 Refactor session metrics and errors
  src/endpoint.rs
  src/endpoint/address.rs
  src/metrics.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/proxy/sessions/error.rs
  src/proxy/sessions/manager.rs
  src/proxy/sessions/metrics.rs
  src/utils.rs
  tests/metrics.rs
Labels: size/l
