Repository EmbarkStudios/quilkin, pull requests merged in 2022-02, with the labels that each got.

#479 Benchmark comparing read and write throughput
  benches/throughput.rs
Labels: kind/feature, area/performance, area/build-tools, size/m

#447 Add matches filter
  Cargo.toml
  build.rs
  docs/src/filters/matches.md
  docs/src/filters/writing_custom_filters.md
  proto/quilkin/extensions/filters/matches/v1alpha1/matches.proto
  src/config/config_type.rs
  src/config/error.rs
  src/filters.rs
  src/filters/capture_bytes.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/debug.rs
  src/filters/error.rs
  src/filters/factory.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/matches.rs
  src/filters/registry.rs
  src/filters/set.rs
  src/filters/token_router.rs
  src/metadata.rs
  src/proxy/config_dump.rs
  src/proxy/health.rs
  src/xds/listener.rs
  tests/matches.rs
Labels: cla: yes, kind/breaking, size/l

#488 Update clap to 3.1
  Cargo.toml
  src/main.rs
Labels: kind/cleanup, priority/high, size/s

#472 Add Pass & Drop filters, Refactor `Match` config
  build.rs
  docs/src/SUMMARY.md
  docs/src/filters/drop.md
  docs/src/filters/match.md
  docs/src/filters/pass.md
  proto/quilkin/extensions/filters/drop/v1alpha1/drop.proto
  proto/quilkin/extensions/filters/match/v1alpha1/match.proto
  proto/quilkin/extensions/filters/pass/v1alpha1/pass.proto
  src/filters.rs
  src/filters/drop.rs
  src/filters/match.rs
  src/filters/match/config.rs
  src/filters/matches.rs
  src/filters/pass.rs
  src/filters/set.rs
  tests/match.rs
Labels: size/xl

#495 Update xds.md
  docs/src/xds.md
Labels: kind/documentation, kind/cleanup, priority/high, size/xs

#498 Update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#497 Update dependencies
  Cargo.toml
Labels: size/s
