Repository EmbarkStudios/quilkin, pull requests merged in 2022-04, with the labels that each got.

#512 Update htmltest for test-docs
  build/build-image/Dockerfile
Labels: kind/bug, area/tests, size/xs

#511 Metrics for Match Filter
  docs/src/filters/match.md
  src/filters/match.rs
  src/filters/match/metrics.rs
Labels: kind/feature, area/operations, size/m

#514 Add conversion to protobuf for most core types
  src/endpoint.rs
  src/endpoint/address.rs
  src/filters/capture/config.rs
  src/filters/compress.rs
  src/filters/compress/config.rs
  src/filters/concatenate_bytes.rs
  src/filters/concatenate_bytes/config.rs
  src/filters/debug.rs
  src/filters/drop.rs
  src/filters/error.rs
  src/filters/firewall.rs
  src/filters/firewall/config.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/config.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/match/config.rs
  src/filters/pass.rs
  src/filters/token_router.rs
  src/metadata.rs
  src/prost.rs
  src/xds/listener.rs
  tests/xds.rs
Labels: size/l

#516 Use htmltest binary not build from source
  build/build-image/Dockerfile
Labels: kind/cleanup, area/build-tools, size/s

#518 Replace serde_yaml with serde_json internally
  src/cluster/shared.rs
  src/config.rs
  src/config/config_type.rs
  src/endpoint.rs
  src/filters/capture.rs
  src/filters/compress.rs
  src/filters/debug.rs
  src/filters/factory.rs
  src/filters/token_router.rs
  src/metadata.rs
  src/prost.rs
  src/xds/cluster.rs
  tests/filters.rs
Labels: size/m

#515 Add `StaticFilter` trait
  docs/src/filters/writing_custom_filters.md
  examples/quilkin-filter-example/src/main.rs
  src/config/config_type.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/concatenate_bytes.rs
  src/filters/debug.rs
  src/filters/drop.rs
  src/filters/error.rs
  src/filters/factory.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/match/config.rs
  src/filters/pass.rs
  src/filters/registry.rs
  src/filters/set.rs
  src/filters/token_router.rs
  src/prost.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/test_utils.rs
  src/xds/listener.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/token_router.rs
Labels: kind/feature, kind/breaking, size/xl

#525 Refactor configuration and builder pattern
  Cargo.toml
  benches/throughput.rs
  docs/src/filters.md
  docs/src/filters/capture.md
  docs/src/filters/compress.md
  docs/src/filters/concatenate_bytes.md
  docs/src/filters/debug.md
  docs/src/filters/firewall.md
  docs/src/filters/load_balancer.md
  docs/src/filters/local_rate_limit.md
  docs/src/filters/match.md
  docs/src/filters/token_router.md
  docs/src/filters/writing_custom_filters.md
  docs/src/proxy-configuration.md
  docs/src/proxy.md
  docs/src/quickstart-netcat.md
  examples/agones-xonotic/client-compress.yaml
  examples/agones-xonotic/sidecar-compress.yaml
  examples/agones-xonotic/sidecar.yaml
  examples/proxy.yaml
  examples/quilkin-filter-example/config.yaml
  examples/quilkin-filter-example/src/main.rs
  image/quilkin.yaml
  src/cluster/shared.rs
  src/config.rs
  src/config/builder.rs
  src/config/error.rs
  src/filters.rs
  src/filters/error.rs
  src/lib.rs
  src/proxy.rs
  src/proxy/admin.rs
  src/proxy/builder.rs
  src/proxy/server.rs
  src/runner.rs
  src/test_utils.rs
  src/xds/ads_client.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/token_router.rs
  tests/xds.rs
Labels: kind/breaking, size/xl

#526 Update to Rust 1.60
  rust-toolchain.toml
Labels: size/xs
