Repository EmbarkStudios/quilkin, pull requests merged in 2022-01, with the labels that each got.

#462 xds: delete snapshot for disconnected proxies
  xds/README.md
  xds/cmd/controller.go
  xds/cmd/file/file.go
  xds/pkg/snapshot/snapshot.go
  xds/pkg/snapshot/snapshot_test.go
Labels: size/m

#464 Document Filter naming conventions
  docs/src/filters/writing_custom_filters.md
Labels: kind/documentation, size/xs

#463 archive_dependencies.sh: Handle no dependencies
  image/archive_dependencies.sh
Labels: kind/bug, area/build-tools, size/s

#457 Completely remove `slog` and replace with `tracing`
  Cargo.toml
  src/cluster/cluster_manager.rs
  src/endpoint/address.rs
  src/filters/manager.rs
  src/lib.rs
  src/proxy.rs
  src/proxy/admin.rs
  src/proxy/builder.rs
  src/proxy/health.rs
  src/proxy/metrics.rs
  src/proxy/server.rs
  src/proxy/server/resource_manager.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
  src/runner.rs
  src/test_utils.rs
  src/xds/ads_client.rs
  src/xds/cluster.rs
  src/xds/listener.rs
  tests/compress.rs
  tests/filters.rs
  tests/firewall.rs
  tests/metrics.rs
  tests/xds.rs
Labels: size/l

#466 Remove `slog-json` from archive_dependencies.sh
  image/archive_dependencies.sh
Labels: kind/cleanup, area/build-tools, size/xs

#465 Fix exponential backoff on xds client retry
  src/xds/ads_client.rs
Labels: kind/bug, area/user-experience, size/s

#467 Remove src/filters/extensions
  src/filters/extensions/concatenate_bytes.rs
  src/filters/extensions/load_balancer.rs
Labels: kind/cleanup, size/l

#468 Consistent implementation of source/dest
  src/filters/chain.rs
  src/filters/debug.rs
  src/filters/firewall.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/local_rate_limit.rs
  src/filters/read.rs
  src/filters/write.rs
  src/proxy/server.rs
  src/proxy/sessions/session.rs
  src/proxy/sessions/session_manager.rs
  src/test_utils.rs
  tests/firewall.rs
Labels: kind/cleanup, size/m

#471 Fix 404 in docs
  docs/src/filters/compress.md
Labels: kind/documentation, kind/cleanup, size/xs

#469 management-server: update metrics and doc
  xds/README.md
  xds/pkg/cluster/agones/agones.go
  xds/pkg/cluster/cluster.go
  xds/pkg/server/callbacks.go
  xds/pkg/snapshot/snapshot.go
Labels: size/m

#473 Update Rust to 1.58.1
  rust-toolchain.toml
  src/config.rs
  src/config/config_type.rs
  src/endpoint.rs
  src/filters/error.rs
  src/filters/firewall/config.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/token_router.rs
  src/main.rs
  src/metrics.rs
  src/proxy/builder.rs
  src/proxy/config_dump.rs
  src/proxy/server/resource_manager.rs
  src/test_utils.rs
  src/xds/ads_client.rs
  src/xds/cluster.rs
  src/xds/listener.rs
  tests/compress.rs
  tests/filter_order.rs
  tests/xds.rs
Labels: size/m

#476 Update dependencies
  Cargo.toml
  macros/Cargo.toml
  src/main.rs
Labels: size/s

#477 Update CODEOWNERS
  CODEOWNERS
Labels: size/xs
