Repository EmbarkStudios/quilkin, pull requests merged in 2022-10, with the labels that each got.

#604 Add ASN maxmind database integration
  Cargo.toml
  about.toml
  deny.toml
  docs/src/proxy.md
  image/archive_dependencies.sh
  src/cli.rs
  src/cli/run.rs
  src/config.rs
  src/config/builder.rs
  src/config/slot.rs
  src/lib.rs
  src/main.rs
  src/maxmind_db.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/proxy/sessions/manager.rs
  src/test_utils.rs
  src/xds/client.rs
  src/xds/server.rs
Labels: size/m

#616 Use `TimedSizedCache`
  src/xds/server.rs
Labels: size/xs

#614 Update to Rust 1.64.0
  rust-toolchain.toml
  src/filters/load_balancer/endpoint_chooser.rs
  src/proxy.rs
Labels: size/xs

#617 Sidecar Example README: Switch to relative paths
  examples/agones-xonotic/README.md
Labels: kind/documentation, area/examples, kind/cleanup, size/xs

#615 Update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#618 Agones xDS Provider example
  build/templates/release-issue.md
  docs/src/examples.md
  docs/src/quickstart-agones-xonotic.md
  examples/agones-xonotic-sidecar/README.md
  examples/agones-xonotic-sidecar/client-compress.yaml
  examples/agones-xonotic-sidecar/sidecar-compress.yaml
  examples/agones-xonotic-sidecar/sidecar.yaml
  examples/agones-xonotic-xds/README.md
  examples/agones-xonotic-xds/client-token.yaml
  examples/agones-xonotic-xds/fleet.yaml
  examples/agones-xonotic-xds/gameserverallocation.yaml
  examples/agones-xonotic-xds/proxy-pool.yaml
  examples/agones-xonotic-xds/xds-control-plane.yaml
Labels: kind/feature, area/examples, size/m

#620 Update dependencies
  Cargo.toml
  agones/Cargo.toml
  agones/src/lib.rs
  agones/src/pod.rs
  agones/src/sidecar.rs
  agones/src/xds.rs
  macros/Cargo.toml
  src/cli/generate_config_schema.rs
  src/config/watch/agones/crd.rs
  src/config/watch/fs.rs
Labels: size/m

#622 Change admin flag to `no-admin`, respect shutdown signal
  src/cli.rs
Labels: size/s

#624 Fix not receiving stream pushes
  src/proxy.rs
  src/xds/server.rs
Labels: size/s

#621 Added ASN and Prefix labels to active sessions
  src/maxmind_db.rs
  src/proxy/sessions.rs
  src/proxy/sessions/metrics.rs
Labels: size/s

#625 Fixes for example Grafana dashboard
  examples/grafana-dashboards/dashboards/dashboard-gameservers.yaml
Labels: kind/bug, area/examples, size/m

#623 Flatten proxy config section into root
  docs/src/filters/writing_custom_filters.md
  docs/src/proxy-configuration.md
  examples/agones-xonotic-sidecar/sidecar-compress.yaml
  examples/control-plane.yaml
  examples/iperf3/proxy.yaml
  examples/proxy.yaml
  examples/quilkin-filter-example/config.yaml
  src/cli/manage.rs
  src/cli/run.rs
  src/config.rs
  src/config/builder.rs
  src/main.rs
  src/proxy.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/server.rs
Labels: size/m

#627 Add timestamp filter
  build.rs
  docs/src/filters/timestamp.md
  proto/quilkin/filters/timestamp/v1alpha1/timestamp.proto
  src/filters.rs
  src/filters/error.rs
  src/filters/set.rs
  src/filters/timestamp.rs
  src/lib.rs
  src/metrics.rs
Labels: size/m

#628 Connect Timestamp Filter to rest of documentation
  docs/src/SUMMARY.md
  docs/src/filters.md
Labels: kind/documentation, kind/cleanup, size/xs

#629 mdbook-variables for Documentation
  .github/workflows/docs.yml
  build/Makefile
  build/build-image/Dockerfile
  docs/book.toml
  docs/src/examples.md
  docs/src/faq.md
  docs/src/filters/writing_custom_filters.md
  docs/src/integrations.md
  docs/src/introduction.md
  docs/src/proxy-configuration.md
  docs/src/quickstart-agones-xonotic.md
  docs/src/quickstart-netcat.md
  docs/src/using.md
  docs/src/xds.md
Labels: kind/documentation, kind/feature, area/build-tools, size/s

#630 Refactor filter model from Context->Response into ref mut Context
  docs/src/filters/writing_custom_filters.md
  examples/quilkin-filter-example/src/main.rs
  src/config/slot.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/concatenate_bytes.rs
  src/filters/debug.rs
  src/filters/drop.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/pass.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/filters/write.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/test_utils.rs
Labels: size/l

#631 Agones: Add token removal test.
  agones/src/xds.rs
Labels: area/tests, kind/cleanup, size/s

#633 Refactor metrics statics into free fns
  src/filters/chain.rs
  src/metrics.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/proxy/sessions/metrics.rs
Labels: size/m

#634 Try to recover when the main process fails
  src/cli.rs
  src/cli/generate_config_schema.rs
  src/cli/manage.rs
  src/cli/run.rs
Labels: size/s

#636 Build macos binaries on ARM
  build/Makefile
  build/darwin-builder/Makefile
  build/darwin-builder/cloudbuild.yaml
Labels: kind/feature, area/build-tools, size/s

#635 Update yaml configuration documentation
  docs/src/SUMMARY.md
  docs/src/admin.md
  docs/src/file-configuration.md
  docs/src/filters/writing_custom_filters.md
  docs/src/proxy.md
  docs/src/quickstart-agones-xonotic.md
  docs/src/quickstart-netcat.md
  docs/src/using.md
  examples/control-plane.yaml
  examples/proxy.yaml
Labels: kind/documentation, kind/cleanup, size/s
