Repository EmbarkStudios/quilkin, pull requests merged in 2023-09, with the labels that each got.

#782 Update dependencies and Rust version
  Cargo.toml
  build.rs
  examples/quilkin-filter-example/Cargo.toml
  rust-toolchain.toml
  src/cli/qcmp.rs
  src/filters/load_balancer.rs
  src/filters/timestamp.rs
  src/protocol.rs
  src/xds/server.rs
Labels: size/m

#781 Late initialise upstream socket to prevent session map lock
  deny.toml
  src/proxy.rs
  src/proxy/sessions.rs
Labels: size/m

#783 README description update
  README.md
Labels: kind/documentation, kind/cleanup, size/xs

#784 add cli option for log formatting (Closes #531)
  Cargo.toml
  src/cli.rs
Labels: size/s

#788 Locally listen on IPv4 and IPv6 addresses
  benches/throughput.rs
  build/Makefile
  docs/src/deployment/admin.md
  docs/src/services/agent.md
  docs/src/services/proxy.md
  docs/src/services/proxy/filters/firewall.md
  docs/src/services/proxy/qcmp.md
  docs/src/services/xds.md
  proto/quilkin/filters/firewall/v1alpha1/firewall.proto
  src/cli.rs
  src/cli/proxy.rs
  src/config.rs
  src/endpoint.rs
  src/endpoint/address.rs
  src/filters/firewall.rs
  src/filters/firewall/config.rs
  src/protocol.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/test_utils.rs
  src/utils/net.rs
  src/xds.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/qcmp.rs
  tests/token_router.rs
Labels: kind/feature, size/xl

#791 fix timestamp warnings
  src/cli/qcmp.rs
  src/protocol.rs
  src/proxy.rs
  src/proxy/sessions.rs
  tests/qcmp.rs
Labels: size/s

#790 Add --idle-request-interval-secs
  src/cli/proxy.rs
  src/cli/relay.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/server.rs
Labels: size/s

#794 [docs] Fix 0.5.0/using.html
  v0.5.0/book/using.html
Labels: kind/bug, kind/documentation

#795 [docs] Fix 0.6.0/installation.html
  v0.6.0/book/installation.html
Labels: kind/bug, kind/documentation

#793 Fix version issue when publishing release docs
  .github/workflows/docs.yml
Labels: kind/bug, kind/documentation, size/xs

#785 Refactor ClusterMap
  agones/src/sidecar.rs
  agones/src/xds.rs
  benches/throughput.rs
  build.rs
  docs/src/deployment/quickstarts/agones-xonotic-xds.md
  docs/src/services/proxy.md
  docs/src/services/proxy/configuration.md
  docs/src/services/proxy/filters.md
  docs/src/services/proxy/filters/capture.md
  docs/src/services/proxy/filters/compress.md
  docs/src/services/proxy/filters/concatenate_bytes.md
  docs/src/services/proxy/filters/debug.md
  docs/src/services/proxy/filters/firewall.md
  docs/src/services/proxy/filters/load_balancer.md
  docs/src/services/proxy/filters/local_rate_limit.md
  docs/src/services/proxy/filters/match.md
  docs/src/services/proxy/filters/timestamp.md
  docs/src/services/proxy/filters/token_router.md
  docs/src/services/proxy/filters/writing_custom_filters.md
  docs/src/services/relay.md
  docs/src/services/xds/providers/filesystem.md
  examples/agones-xonotic-sidecar/client-compress.yaml
  examples/agones-xonotic-sidecar/sidecar-compress.yaml
  examples/agones-xonotic-xds/client-token.yaml
  examples/iperf3/proxy.yaml
  examples/proxy.yaml
  examples/quilkin-filter-example/src/main.rs
  proto/quilkin/config/v1alpha1/config.proto
  src/admin.rs
  src/cli.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cluster.rs
  src/config.rs
  src/config/providers/k8s.rs
  src/config/providers/k8s/agones.rs
  src/config/watch/fs.rs
  src/endpoint.rs
  src/endpoint/address.rs
  src/endpoint/locality.rs
  src/metadata.rs
  src/prost.rs
  src/test_utils.rs
  src/xds.rs
  src/xds/resource.rs
  src/xds/server.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/token_router.rs
Labels: size/xl

#799 Update to the latest Xonotic release.
  examples/agones-xonotic-sidecar/sidecar-compress.yaml
  examples/agones-xonotic-sidecar/sidecar.yaml
  examples/agones-xonotic-xds/fleet.yaml
Labels: area/examples, kind/cleanup, size/xs

#801 Fix broken Envoy link.
  docs/src/services/xds/metrics.md
Labels: kind/documentation, kind/cleanup, size/xs

#803 Update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#800 Change quickstart example README.md to point to docs.
  examples/agones-xonotic-sidecar/README.md
  examples/agones-xonotic-xds/README.md
  examples/quilkin-filter-example/README.md
Labels: kind/documentation, area/examples, kind/cleanup, size/m

#805 Update to Distroless based on Debian 12
  image/Dockerfile
Labels: area/security, kind/cleanup, size/xs
