Repository EmbarkStudios/quilkin, pull requests merged in 2023-08, with the labels that each got.

#765 Add test for Cluster::merge
  src/cluster.rs
  src/config.rs
  src/endpoint/locality.rs
Labels: size/m

#766 Automatically update approved PRs with automerge
  .github/workflows/pr_update.yml
Labels: area/build-tools, size/s

#767 Update to Rust 1.71.1 (cargo CVE-2023-38497)
  agones/src/sidecar.rs
  rust-toolchain.toml
  src/endpoint/locality.rs
  tests/filter_order.rs
Labels: area/security, area/build-tools, size/xs

#768 Small doc improvements
  docs/src/deployment/admin.md
  docs/src/deployment/quickstarts/agones-xonotic-xds.md
Labels: kind/documentation, size/s

#773 Fix watch on clusters, by removing inner Arc
  Cargo.toml
  src/admin.rs
  src/cli.rs
  src/cli/proxy.rs
  src/cluster.rs
  src/config.rs
  src/config/providers/k8s.rs
  src/config/watch.rs
  src/proxy.rs
  src/test_utils.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/server.rs
Labels: size/m

#774 Add logging for what endpoints are added and removed
  src/cluster.rs
  src/config.rs
  src/endpoint/locality.rs
Labels: size/s

#776 Update Tokio: 1.32.0
  Cargo.toml
Labels: kind/cleanup, size/xs

#770 Add `qcmp ping` command
  docs/src/services/proxy/qcmp.md
  src/cli.rs
  src/cli/qcmp.rs
  src/protocol.rs
Labels: size/m

#779 Security: Update trust-dns-resolver
  Cargo.toml
  deny.toml
  src/endpoint/address.rs
Labels: area/security, kind/cleanup, size/s
