Repository EmbarkStudios/quilkin, pull requests merged in 2023-01, with the labels that each got.

#674 Replace SessionManager with TtlMap, refactor downstream packet processing to track more errors in metrics
  src/endpoint.rs
  src/endpoint/address.rs
  src/filters/local_rate_limit.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/proxy/sessions/manager.rs
  src/ttl_map.rs
Labels: size/xl

#675 Make: package_version less brittle
  build/Makefile
Labels: kind/cleanup, area/build-tools, size/xs

#678 Docs: `quilkin run` vs `proxy` bug in preprocessor
  docs/preprocessor.sh
  docs/src/proxy-mode.md
Labels: kind/bug, kind/documentation, size/xs

#670 Update dependencies
  Cargo.toml
  agones/Cargo.toml
  src/config.rs
  src/filters/concatenate_bytes/config.rs
Labels: size/s

#679 Release 0.5.0
  CHANGELOG.md
  Cargo.toml
  README.md
  build/release/cloudbuild.yaml
  macros/Cargo.toml
Labels: kind/release, size/s

#681 Updates for 0.6.0-dev
  Cargo.toml
  build/templates/github-release.md
  macros/Cargo.toml
Labels: kind/release, size/xs

#684 Add warning when watcher fails to send an update
  src/xds/server.rs
Labels: size/xs

#683 Add hotfix around xDS stream sometimes not responding with changes
  src/xds/client.rs
  src/xds/server.rs
Labels: kind/bug, size/m

#692 Remove unneeded pin requirement
  src/xds/server.rs
Labels: size/s

#688 Refactor documentation layout and define default ports
  agones/src/lib.rs
  agones/src/sidecar.rs
  agones/src/xds.rs
  build/Makefile
  docs/book.toml
  docs/src/SUMMARY.md
  docs/src/admin.md
  docs/src/deployment/admin.md
  docs/src/deployment/configuration.md
  docs/src/deployment/examples.md
  docs/src/deployment/quickstarts/_agones.md
  docs/src/deployment/quickstarts/agones-xonotic-sidecar.md
  docs/src/deployment/quickstarts/agones-xonotic-xds.md
  docs/src/deployment/quickstarts/netcat.md
  docs/src/deployment/quickstarts/xonotic-address.png
  docs/src/examples.md
  docs/src/faq.md
  docs/src/installation.md
  docs/src/introduction.md
  docs/src/proxy-mode.md
  docs/src/proxy/maxmind.md
  docs/src/quickstart.md
  docs/src/sdks.md
  docs/src/services/proxy.md
  docs/src/services/proxy/filters.md
  docs/src/services/proxy/filters/capture.md
  docs/src/services/proxy/filters/compress.md
  docs/src/services/proxy/filters/concatenate_bytes.md
  docs/src/services/proxy/filters/debug.md
  docs/src/services/proxy/filters/drop.md
  docs/src/services/proxy/filters/firewall.md
  docs/src/services/proxy/filters/load_balancer.md
  docs/src/services/proxy/filters/local_rate_limit.md
  docs/src/services/proxy/filters/match.md
  docs/src/services/proxy/filters/pass.md
  docs/src/services/proxy/filters/timestamp.md
  docs/src/services/proxy/filters/token_router.md
  docs/src/services/proxy/filters/writing_custom_filters.md
  docs/src/services/proxy/metrics.md
  docs/src/services/xds.md
  docs/src/services/xds/metrics.md
  docs/src/services/xds/providers/agones.md
  docs/src/services/xds/providers/filesystem.md
  docs/src/using.md
  docs/src/xds/builtin.md
  src/cli.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/config.rs
  src/config/slot.rs
  src/lib.rs
Labels: kind/documentation, kind/cleanup, kind/breaking, size/l

#693 Migrate image to supported distroless tag
  image/Dockerfile
Labels: area/security, kind/cleanup, size/xs

#694 Strip Config of all service specific configuration for now
  agones/src/xds.rs
  benches/throughput.rs
  docs/src/deployment/admin.md
  docs/src/deployment/configuration.md
  docs/src/services/proxy/filters.md
  docs/src/services/proxy/filters/capture.md
  docs/src/services/proxy/filters/compress.md
  docs/src/services/proxy/filters/concatenate_bytes.md
  docs/src/services/proxy/filters/debug.md
  docs/src/services/proxy/filters/firewall.md
  docs/src/services/proxy/filters/load_balancer.md
  docs/src/services/proxy/filters/local_rate_limit.md
  docs/src/services/proxy/filters/match.md
  docs/src/services/proxy/filters/timestamp.md
  docs/src/services/proxy/filters/token_router.md
  docs/src/services/proxy/filters/writing_custom_filters.md
  docs/src/services/xds.md
  docs/src/services/xds/providers/filesystem.md
  docs/src/xds/providers/filesystem.md
  examples/agones-xonotic-xds/client-token.yaml
  examples/control-plane.yaml
  examples/proxy.yaml
  examples/quilkin-filter-example/src/main.rs
  src/admin.rs
  src/cli.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cluster.rs
  src/config.rs
  src/config/builder.rs
  src/config/metrics.rs
  src/filters.rs
  src/filters/chain.rs
  src/lib.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/test_utils.rs
  src/ttl_map.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/server.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate_bytes.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/token_router.rs
Labels: size/xl
