Repository EmbarkStudios/quilkin, pull requests merged in 2023-07, with the labels that each got.

#748 Downgrade trust-dns-resolver
  Cargo.toml
Labels: size/xs

#757 Add GDC presentation to documentation.
  docs/src/SUMMARY.md
  docs/src/third-party/presentations.md
  docs/src/third-party/vault.png
Labels: kind/documentation, size/s

#758 Release 0.6.0
  CHANGELOG.md
  Cargo.toml
  README.md
  build/release/README.md
  build/templates/release-issue.md
  macros/Cargo.toml
Labels: kind/release, size/s

#759 Prep: 0.7.0-dev
  Cargo.toml
  build/templates/github-release.md
  build/templates/release-issue.md
  docs/htmltest.yaml
  docs/src/installation.md
  macros/Cargo.toml
Labels: kind/release, size/s

#741 Move QCMP to a seperate port
  benches/throughput.rs
  docs/src/services/proxy.md
  docs/src/services/proxy/qcmp.md
  src/cli/proxy.rs
  src/protocol.rs
  src/proxy.rs
  tests/qcmp.rs
Labels: size/s

#760 Update Agones to 1.33.0
  Cargo.toml
  agones/helm.yaml
  agones/main.tf
Labels: area/security, kind/cleanup, size/s

#762 Unit and integration test debugging enhancements
  Cargo.toml
  agones/Cargo.toml
  agones/src/lib.rs
  agones/src/xds.rs
  src/test_utils.rs
Labels: kind/feature, area/tests, size/m

#763 Agones: Update simple-game-server image to latest
  agones/src/lib.rs
Labels: area/security, area/tests, kind/cleanup, size/xs

#764 Fix: mdbook-variables failing on doc building.
  .github/workflows/docs.yml
  build/build-image/Dockerfile
Labels: kind/bug, area/build-tools, size/xs
