Repository EmbarkStudios/quilkin, pull requests merged in 2023-02, with the labels that each got.

#696 Add region parameters for control planes
  src/cli/manage.rs
  src/cluster.rs
  src/config.rs
  src/config/watch/agones.rs
  src/config/watch/fs.rs
  src/endpoint.rs
  src/endpoint/locality.rs
  tests/metrics.rs
Labels: kind/feature, size/m

#698 Add initial implementation of relay service
  Cargo.toml
  build.rs
  build/build-image/Dockerfile
  docs/preprocessor.sh
  docs/src/SUMMARY.md
  docs/src/services/relay.md
  proto/quilkin/relay/v1alpha1/relay.proto
  src/admin.rs
  src/cli.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cli/relay.rs
  src/cluster.rs
  src/config.rs
  src/config/watch.rs
  src/config/watch/agones.rs
  src/endpoint/locality.rs
  src/proxy.rs
  src/test_utils.rs
  src/utils/net.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/metrics.rs
  src/xds/server.rs
  tests/metrics.rs
Labels: size/xl

#702 Refactor provider task retrying and move providers to their own module
  src/cli.rs
  src/cli/manage.rs
  src/config.rs
  src/config/provider.rs
Labels: size/m

#705 Workaround for mdbook-variables
  .github/workflows/docs.yml
  build/build-image/Dockerfile
Labels: kind/bug, area/build-tools, size/xs

#706 Add debug line for cli parameters
  src/cli.rs
  src/cli/generate_config_schema.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cli/relay.rs
Labels: size/s

#703 Add filter chain discovery to the relay
  agones/src/lib.rs
  agones/src/sidecar.rs
  agones/src/xds.rs
  src/cli/relay.rs
  src/config.rs
  src/config/providers.rs
  src/config/providers/k8s.rs
  src/config/providers/k8s/agones.rs
  src/config/watch/agones.rs
Labels: size/m

#707 Add environment variables to config providers
  src/config/providers.rs
Labels: size/s

#709 Don't drop the stream client until the function completes
  src/cli/proxy.rs
Labels: size/xs

#710 Add test for relay proxy routing (and support for file providers)
  Cargo.toml
  src/cli.rs
  src/cli/manage.rs
  src/cli/relay.rs
  src/config.rs
  src/config/providers.rs
  src/config/watch/fs.rs
  src/endpoint.rs
  src/filters/chain.rs
  src/lib.rs
  src/xds/client.rs
Labels: size/m

#713 Recover when stream channel breaks
  src/xds/client.rs
Labels: size/s
