Repository EmbarkStudios/quilkin, pull requests merged in 2023-11, with the labels that each got.

#841 Move admin server to separate OS thread
  src/cli/admin.rs
Labels: size/s

#842 Remove spawn task for each packet.
  src/cli/proxy.rs
Labels: size/s

#845 Move cluster into net
  src/config.rs
  src/lib.rs
  src/net.rs
  src/net/cluster.rs
  src/net/endpoint.rs
  src/net/endpoint/locality.rs
  src/net/xds.rs
  src/net/xds/resource.rs
Labels: size/s

#843 Move pipeline errors from metrics to a fixed interval report
  src/cli/proxy.rs
Labels: size/s

#844 Update kubernetes watch configuration to prioritise performance
  src/config/providers/k8s.rs
Labels: size/s

#846 Minor cleanup
  Cargo.toml
  deny.toml
  src/cli.rs
  src/filters/drop.rs
  src/filters/pass.rs
Labels: size/s

#848 Update xds client
  src/net/xds.rs
Labels: size/xs

#847 Remove built dependency
  Cargo.toml
  build.rs
  src/net/endpoint/metadata.rs
Labels: size/s

#849 Remove unwraps from proxy::sessions
  src/cli/proxy.rs
  src/cli/proxy/sessions.rs
Labels: size/s

#853 Refactor benchmarks
  Cargo.toml
  benches/read_write.rs
  benches/shared.rs
  benches/throughput.rs
  examples/quilkin-filter-example/src/main.rs
  src/cli.rs
  src/cli/agent.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cli/proxy/sessions.rs
  src/cli/relay.rs
  src/lib.rs
  src/net/maxmind_db.rs
  src/net/xds.rs
  src/test.rs
  tests/qcmp.rs
Labels: size/l

#855 Use ClusterMap for Filter::read
  src/cli/proxy.rs
  src/config.rs
  src/config/watch.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/net/cluster.rs
  src/test.rs
Labels: size/m

#859 Update to Rust 1.74.0
  rust-toolchain.toml
  src/codec/prost.rs
Labels: size/xs

#850 Move game traffic sockets to io-uring
  Cargo.toml
  benches/shared.rs
  docs/src/services/proxy/filters/writing_custom_filters.md
  examples/quilkin-filter-example/src/main.rs
  src/cli.rs
  src/cli/proxy.rs
  src/cli/proxy/sessions.rs
  src/codec/qcmp.rs
  src/config.rs
  src/config/providers/k8s.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/capture/affix.rs
  src/filters/capture/regex.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/compress/compressor.rs
  src/filters/compress/config.rs
  src/filters/concatenate.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/filters/write.rs
  src/lib.rs
  src/main.rs
  src/net.rs
  src/net/cluster.rs
  src/net/xds.rs
  src/pool.rs
  src/test.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/qcmp.rs
  tests/token_router.rs
Labels: size/xl

#867 Commit Cargo.lock
  .gitignore
  Cargo.lock
  deny.toml
Labels: size/xl

#869 Fix PoolBuffer::split
  Cargo.lock
  src/filters/capture/affix.rs
  src/pool.rs
  tests/filter_order.rs
Labels: size/m

#868 Add lz4 support
  Cargo.lock
  Cargo.toml
  benches/compression.rs
  benches/shared.rs
  docs/src/services/proxy/filters/compress.md
  proto/quilkin/filters/compress/v1alpha1/compress.proto
  src/filters/compress.rs
  src/filters/compress/compressor.rs
  src/filters/compress/config.rs
  src/lib.rs
  src/pool.rs
  tests/filter_order.rs
Labels: size/m

#870 Add Configurable gRPC message size environment variable
  src/config.rs
  src/net/xds/client.rs
  src/net/xds/server.rs
Labels: size/s

#871 Move xDS proxy task to its own thread+runtime
  src/cli/proxy.rs
Labels: size/s

#876 Remove Watch requirements on Clone/PartialEq
  src/cli/admin.rs
  src/codec/base64.rs
  src/config.rs
  src/config/providers/k8s/agones.rs
  src/config/watch.rs
  src/filters/chain.rs
  src/net/cluster.rs
  src/net/xds.rs
  src/net/xds/client.rs
  src/net/xds/server.rs
  src/test.rs
Labels: size/m

#878 Fix: warning: failed to get HEAD path
  build.rs
  build/build-image/Dockerfile
Labels: kind/bug, area/build-tools, size/s

#879 Change debug symbols profile release -> bench
  Cargo.lock
  Cargo.toml
Labels: size/m
