Repository EmbarkStudios/quilkin, pull requests merged in 2023-10, with the labels that each got.

#807 Examples for relay configuration
  examples/agones-xonotic-relay/README.md
  examples/agones-xonotic-relay/client-token.yaml
  examples/agones-xonotic-relay/fleet.yaml
  examples/agones-xonotic-relay/gameserverallocation.yaml
  examples/agones-xonotic-relay/proxy-pool.yaml
  examples/agones-xonotic-relay/relay-control-plane.yaml
Labels: kind/feature, size/m

#808 Update Existing Examples and Quickstarts
  docs/src/deployment/quickstarts/agones-xonotic-sidecar.md
  docs/src/deployment/quickstarts/agones-xonotic-xds.md
  docs/src/deployment/quickstarts/xonotic-address-v6.png
  docs/src/deployment/quickstarts/xonotic-address.png
  examples/agones-xonotic-sidecar/sidecar-compress.yaml
  examples/agones-xonotic-sidecar/sidecar.yaml
  examples/agones-xonotic-xds/proxy-pool.yaml
  examples/agones-xonotic-xds/xds-control-plane.yaml
Labels: kind/cleanup, size/m

#772 Add quickstart for the relay setup
  docs/preprocessor.sh
  docs/src/SUMMARY.md
  docs/src/deployment/quickstarts/agones-xonotic-relay.md
  docs/src/services/agent.md
  docs/src/services/relay.md
Labels: size/m

#810 Update dependencies
  Cargo.toml
Labels: size/s

#811 Integration tests for Agones Relay and Agent
  agones/Cargo.toml
  agones/src/lib.rs
  agones/src/provider.rs
  agones/src/relay.rs
  agones/src/xds.rs
  src/cli.rs
Labels: kind/feature, area/tests, size/xl

#813 Rename: ConcatenateBytes ➡️ Concatenate
  agones/src/sidecar.rs
  build.rs
  cloudbuild.yaml
  docs/src/SUMMARY.md
  docs/src/deployment/quickstarts/agones-xonotic-relay.md
  docs/src/deployment/quickstarts/agones-xonotic-xds.md
  docs/src/services/proxy/filters.md
  docs/src/services/proxy/filters/capture.md
  docs/src/services/proxy/filters/concatenate.md
  docs/src/services/proxy/filters/token_router.md
  examples/agones-xonotic-relay/client-token.yaml
  examples/agones-xonotic-xds/client-token.yaml
  proto/quilkin/filters/concatenate/v1alpha1/concatenate.proto
  src/filters.rs
  src/filters/concatenate.rs
  src/filters/concatenate/config.rs
  src/filters/set.rs
  src/lib.rs
  src/xds.rs
  tests/concatenate.rs
  tests/filter_order.rs
  tests/match.rs
Labels: kind/cleanup, kind/breaking, size/m

#812 Docs: Connect Agent and Relay to Providers
  docs/src/services/agent.md
  docs/src/services/relay.md
  docs/src/services/xds.md
Labels: kind/cleanup, size/xs

#817 Cloud Build: Put logs back in public bucket
  cloudbuild.yaml
Labels: area/tests, size/xs

#802 Add health checks for each service
  benches/throughput.rs
  docs/src/deployment/admin.md
  examples/quilkin-filter-example/src/main.rs
  src/admin.rs
  src/cli.rs
  src/cli/admin.rs
  src/cli/admin/health.rs
  src/cli/agent.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cli/relay.rs
  src/config/providers.rs
  src/config/watch/agones.rs
  src/config/watch/fs.rs
  src/lib.rs
  src/test_utils.rs
  src/xds.rs
  src/xds/client.rs
  src/xds/server.rs
  tests/qcmp.rs
Labels: size/l

#821 Examples: Update readiness and liveness checks.
  docs/src/deployment/admin.md
  examples/agones-xonotic-relay/proxy-pool.yaml
  examples/agones-xonotic-relay/relay-control-plane.yaml
  examples/agones-xonotic-xds/proxy-pool.yaml
  examples/agones-xonotic-xds/xds-control-plane.yaml
Labels: area/examples, size/s

#815 Refactor sessions to use socket pool
  benches/throughput.rs
  src/cli.rs
  src/cli/proxy.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/debug.rs
  src/filters/firewall.rs
  src/filters/match.rs
  src/filters/registry.rs
  src/filters/write.rs
  src/proxy.rs
  src/proxy/sessions.rs
  src/test_utils.rs
  src/ttl_map.rs
  src/utils/net.rs
  src/xds.rs
  tests/capture.rs
  tests/compress.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/token_router.rs
Labels: size/xl

#823 Make noisy relay logs debug
  src/xds/server.rs
Labels: size/xs

#826 Fix dead lock in SessionPool
  src/proxy/sessions.rs
  src/ttl_map.rs
Labels: size/m

#827 Loadtesting fixes
  src/cli.rs
  src/cli/proxy.rs
  src/cli/proxy/sessions.rs
  src/codec/qcmp.rs
  src/net/xds.rs
Labels: size/m

#830 Release 0.7.0
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/src/deployment/quickstarts/agones-xonotic-relay.md
  docs/src/deployment/quickstarts/agones-xonotic-xds.md
  macros/Cargo.toml
Labels: kind/release, size/s

#831 Prep for 0.8.0
  Cargo.toml
  macros/Cargo.toml
Labels: kind/release, size/xs

#840 Update max_delay to 2 sec
  src/config/providers.rs
Labels: size/xs
