Repository EmbarkStudios/quilkin, pull requests merged in 2024-10, with the labels that each got.

#1025 Ignore failing tests on macOS
  src/codec/qcmp.rs
  src/components/proxy/sessions.rs
  src/net.rs
  src/net/phoenix.rs
  src/test.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/qcmp.rs
  tests/token_router.rs
Labels: size/s, kind/other

#1014 improvement: add note about measure units of jitter metric
  docs/src/services/proxy/metrics.md
Labels: kind/documentation, size/xs

#1023 perf: make filters synchronous
  crates/test/tests/proxy.rs
  docs/src/services/proxy/filters/writing_custom_filters.md
  examples/quilkin-filter-example/src/main.rs
  src/components/proxy.rs
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/io_uring.rs
  src/components/proxy/packet_router/reference.rs
  src/components/proxy/sessions.rs
  src/components/proxy/sessions/io_uring.rs
  src/components/proxy/sessions/reference.rs
  src/config/slot.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/concatenate.rs
  src/filters/debug.rs
  src/filters/drop.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/pass.rs
  src/filters/registry.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/net.rs
  src/net/endpoint/address.rs
  src/test.rs
  tests/capture.rs
  tests/filter_order.rs
  tests/token_router.rs
Labels: size/l, kind/other

#1028 perf: Replace hash usage with gxhash
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  build/build-image/Dockerfile
  cloudbuild.yaml
  src/components/proxy/error.rs
  src/components/proxy/packet_router.rs
  src/config.rs
  src/filters/read.rs
  src/filters/write.rs
  src/net/cluster.rs
  src/net/endpoint/metadata.rs
Labels: size/s, kind/other

#1017 Update to Rust 1.81.0
  Cargo.lock
  Cargo.toml
  benches/cluster_map.rs
  benches/misc.rs
  rust-toolchain.toml
  src/config/providers/k8s/agones.rs
  src/filters/factory.rs
  src/filters/local_rate_limit.rs
  src/metrics.rs
Labels: size/m, kind/other

#1032 perf: Use LTO in image builds
  Cargo.toml
  build/Makefile
Labels: size/s, kind/other

#1022 Feature/update management server
  src/cli/manage.rs
  src/components/manage.rs
Labels: kind/feature, size/s
