Repository EmbarkStudios/quilkin, pull requests merged in 2024-12, with the labels that each got.

#1045 Update to Rust 1.83.0
  rust-toolchain.toml
  src/collections/ttl.rs
  src/config/watch.rs
  src/filters/firewall/config.rs
  src/metrics.rs
  src/net/maxmind_db.rs
Labels: size/s, kind/other

#1046 chore: update phoenix log levels
  src/net/phoenix.rs
Labels: size/xs, kind/other

#1047 feat: Add more metrics around phoenix and game traffic
  src/cli.rs
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router/reference.rs
  src/metrics.rs
  src/net/phoenix.rs
Labels: size/m, kind/other

#1049 Don't shutdown io-uring loop on session shutdown
  deny.toml
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/sessions.rs
Labels: size/s, kind/other

#1050 Docs for new metrics (shutdown, qcmp, etc)
  docs/src/deployment/admin.md
  docs/src/services/proxy/metrics.md
  docs/src/services/proxy/qcmp.md
Labels: kind/documentation, size/s
