Repository EmbarkStudios/quilkin, pull requests merged in 2024-08, with the labels that each got.

#991 Reduce ASN related allocations
  src/components/proxy.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
  src/components/proxy/sessions/inner_metrics.rs
  src/metrics.rs
  src/net/maxmind_db.rs
Labels: size/m, kind/other

#982 Generate reference docs from proto files
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
  crates/proto-gen/Cargo.toml
  crates/proto-gen/gen.rs
  crates/quilkin-proto/Cargo.toml
  crates/quilkin-proto/src/generated/quilkin/relay/v1alpha1.rs
  crates/test/Cargo.toml
  docs/htmltest.yaml
  docs/src/SUMMARY.md
  docs/src/services/xds.md
  docs/src/services/xds/proto/index.md
  proto/quilkin/config/v1alpha1/config.proto
  proto/quilkin/relay/v1alpha1/relay.proto
Labels: kind/documentation, size/xl

#992 Update crates/cargo-deny
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/test/Cargo.toml
  crates/xds/Cargo.toml
  deny.toml
  src/config/providers/k8s.rs
Labels: size/xl, kind/other

#987 Cap error heap usage
  crates/gen.rs
  crates/proto-gen/gen.rs
  crates/test/src/lib.rs
  crates/test/tests/mesh.rs
  crates/test/tests/proxy.rs
  crates/xds/src/server.rs
  src/cli/proxy.rs
  src/components/proxy.rs
  src/components/proxy/error.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
  src/filters/capture.rs
  src/filters/compress.rs
  src/filters/drop.rs
  src/filters/error.rs
  src/filters/firewall.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/registry.rs
  src/filters/token_router.rs
  src/net.rs
  src/test.rs
Labels: size/l, kind/other

#993 Replace `tokio-uring` with `io-uring`
  Cargo.lock
  Cargo.toml
  crates/agones/Cargo.toml
  crates/macros/Cargo.toml
  crates/quilkin-proto/Cargo.toml
  crates/test/Cargo.toml
  crates/test/tests/proxy.rs
  src/codec/qcmp.rs
  src/components/agent.rs
  src/components/proxy.rs
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/io_uring.rs
  src/components/proxy/packet_router/reference.rs
  src/components/proxy/sessions.rs
  src/components/proxy/sessions/inner_metrics.rs
  src/components/proxy/sessions/io_uring.rs
  src/components/proxy/sessions/reference.rs
  src/metrics.rs
  src/net.rs
  src/net/phoenix.rs
  src/pool.rs
Labels: size/xl, kind/other

#997 Update project to beta status
  README.md
Labels: size/xs, kind/other

#999 Add Apache Headers to those that are missing
  src/components.rs
  src/components/agent.rs
  src/components/manage.rs
  src/components/proxy.rs
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/io_uring.rs
  src/components/proxy/packet_router/reference.rs
  src/components/proxy/sessions/io_uring.rs
  src/components/proxy/sessions/reference.rs
  src/components/relay.rs
  src/config/providers.rs
  src/config/providers/k8s.rs
  src/filters/capture/affix.rs
  src/filters/capture/regex.rs
  src/net/maxmind_db.rs
  src/net/phoenix.rs
  src/pool.rs
  src/time.rs
  src/xds.rs
Labels: kind/cleanup, size/m

#998 Add basic heap stats
  Cargo.lock
  Cargo.toml
  src/alloc.rs
  src/alloc/metrics.rs
  src/alloc/tracking.rs
  src/cli.rs
  src/lib.rs
Labels: size/m, kind/other

#1000 Docs for Heap Allocation Metrics
  docs/src/deployment/admin.md
Labels: kind/documentation, size/s

#1001 Build: More explicit container caching
  build/Makefile
  cloudbuild.yaml
Labels: kind/cleanup, size/xs

#996 Release 0.9.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  build/templates/release-issue.md
  crates/macros/Cargo.toml
Labels: kind/release, size/s

#1002 Unstick release 0.9.0
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  build/templates/release-issue.md
  crates/quilkin-proto/Cargo.toml
  crates/xds/Cargo.toml
  src/config.rs
  src/filters/token_router.rs
  src/net.rs
  src/net/endpoint.rs
  src/xds.rs
Labels: kind/bug, kind/release, size/m

#1003 Preparation for 0.10.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/macros/Cargo.toml
  crates/quilkin-proto/Cargo.toml
  crates/xds/Cargo.toml
Labels: kind/release, size/s

#1006 Increase timeout of QCMP distance measurement
  src/codec/qcmp.rs
Labels: size/xs, kind/other

#1008 Don't panic if there are no updates available
  crates/xds/src/server.rs
Labels: size/xs, kind/other

#1009 Update Examples to 0.9.0
  build/templates/release-issue.md
  examples/agones-xonotic-relay/proxy-pool.yaml
  examples/agones-xonotic-relay/relay-control-plane.yaml
  examples/agones-xonotic-sidecar/sidecar-compress.yaml
  examples/agones-xonotic-sidecar/sidecar.yaml
  examples/agones-xonotic-xds/proxy-pool.yaml
  examples/agones-xonotic-xds/xds-control-plane.yaml
Labels: area/examples, kind/cleanup, size/s

#1010 Test: Concurrent clients for TokenRouter
  tests/token_router.rs
Labels: area/tests, kind/cleanup, size/m
