Repository EmbarkStudios/quilkin, pull requests merged in 2024-03, with the labels that each got.

#898 Remove protobuf_src from example
  examples/quilkin-filter-example/Cargo.toml
  examples/quilkin-filter-example/build.rs
  examples/quilkin-filter-example/src/generated.rs
  examples/quilkin-filter-example/src/generated/greet.rs
  examples/quilkin-filter-example/src/main.rs
Labels: size/s

#899 Move non-linux builds to github
  .github/workflows/ci.yml
  build/Makefile
  cloudbuild.yaml
Labels: size/s

#901 Use newly published deny
  .github/workflows/ci.yml
  src/cli/proxy.rs
  src/net/xds.rs
  src/test.rs
Labels: size/xs

#903 Build: Https on packages.cloud.google.com
  build/build-image/Dockerfile
Labels: kind/bug, area/build-tools

#905 Add licence.html to release quilkin.zip
  build/Makefile
Labels: kind/cleanup, size/s

#906 Release 0.8.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  macros/Cargo.toml
Labels: kind/release, size/s

#908 Prep for 0.9.0-dev
  Cargo.lock
  Cargo.toml
  macros/Cargo.toml
Labels: kind/release, size/s

#909 Test refactor proposal
  Cargo.lock
  Cargo.toml
  agones/src/provider.rs
  benches/shared.rs
  build/Makefile
  examples/quilkin-filter-example/src/main.rs
  src/cli.rs
  src/cli/agent.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cli/relay.rs
  src/codec/qcmp.rs
  src/components.rs
  src/components/admin.rs
  src/components/admin/health.rs
  src/components/agent.rs
  src/components/manage.rs
  src/components/proxy.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
  src/components/proxy/sessions/metrics.rs
  src/components/relay.rs
  src/config.rs
  src/config/watch/fs.rs
  src/config/xds.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/capture/config.rs
  src/filters/metadata.rs
  src/filters/token_router.rs
  src/lib.rs
  src/net.rs
  src/net/cluster.rs
  src/net/endpoint.rs
  src/net/phoenix.rs
  src/net/xds.rs
  src/net/xds/client.rs
  src/net/xds/server.rs
  src/test.rs
  test/Cargo.toml
  test/src/lib.rs
  test/tests/mesh.rs
  test/tests/proxy.rs
  tests/capture.rs
  tests/compress.rs
  tests/concatenate.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/health.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/metrics.rs
  tests/no_filter.rs
  tests/qcmp.rs
  tests/token_router.rs
Labels: size/xl

#912 Update to Rust 1.77.0
  benches/cluster_map.rs
  benches/shared.rs
  rust-toolchain.toml
  src/components/admin.rs
  src/components/agent.rs
  src/components/manage.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
  src/config.rs
  src/config/providers/k8s.rs
  src/config/slot.rs
  src/net.rs
  src/net/xds/resource.rs
  src/net/xds/server.rs
Labels: size/s

#915 Make idle request logs debug
  src/net/xds/client.rs
Labels: size/xs

#917 Add change detection log
  src/net/phoenix.rs
Labels: size/xs
