Repository EmbarkStudios/quilkin, pull requests merged in 2024-11, with the labels that each got.

#1027 perf: Use enum_dispatch over dynamic dispatch
  Cargo.lock
  Cargo.toml
  build/Makefile
  cloudbuild.yaml
  docs/src/SUMMARY.md
  docs/src/services/proxy/filters.md
  docs/src/services/proxy/filters/writing_custom_filters.md
  examples/quilkin-filter-example/.gitignore
  examples/quilkin-filter-example/Cargo.toml
  examples/quilkin-filter-example/README.md
  examples/quilkin-filter-example/config.yaml
  examples/quilkin-filter-example/src/generated.rs
  examples/quilkin-filter-example/src/generated/greet.rs
  examples/quilkin-filter-example/src/greet.proto
  examples/quilkin-filter-example/src/main.rs
  src/filters.rs
  src/filters/chain.rs
  src/filters/factory.rs
  src/lib.rs
Labels: size/l, kind/other

#1040 chore: update dependencies
  Cargo.lock
  Cargo.toml
  about.toml
  crates/agones/Cargo.toml
  crates/agones/src/sidecar.rs
  crates/macros/Cargo.toml
  crates/test/tests/proxy.rs
  deny.toml
  src/net/cluster.rs
Labels: size/xl, kind/other

#1041 fix: Guard against invalid gameserver events
  src/config/providers/k8s.rs
Labels: size/s, kind/other

#1042 Remove destination address allocation
  .cargo/config.toml
  Cargo.lock
  benches/token_router.rs
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/io_uring.rs
  src/components/proxy/packet_router/reference.rs
  src/config/slot.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/concatenate.rs
  src/filters/debug.rs
  src/filters/drop.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/pass.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/net/cluster.rs
  src/test.rs
Labels: size/m, kind/other

#1043 Remove async channels for pushing buffers to be sent
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/test/Cargo.toml
  crates/test/tests/proxy.rs
  src/collections/ttl.rs
  src/components/proxy.rs
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/io_uring.rs
  src/components/proxy/packet_router/reference.rs
  src/components/proxy/sessions.rs
  src/components/proxy/sessions/io_uring.rs
  src/components/proxy/sessions/reference.rs
Labels: size/l, kind/other
