Repository EmbarkStudios/quilkin, pull requests merged in 2024-02, with the labels that each got.

#892 Send back an empty delta response for initial `ignore-me`
  src/config/xds.rs
  src/net/xds/server.rs
Labels: size/s

#872 Make the ready check has endpoints OR has xDS connection
  docs/src/deployment/admin.md
  src/cli/proxy.rs
Labels: size/xs

#875 Add pprof endpoint
  Cargo.lock
  Cargo.toml
  about.toml
  docs/src/deployment/admin.md
  src/cli/admin.rs
Labels: size/l

#856 ClusterMap benchmarks
  Cargo.lock
  Cargo.toml
  about.toml
  benches/cluster_map.rs
  deny.toml
  macros/src/include.rs
  src/cli/agent.rs
  src/cli/manage.rs
  src/net.rs
  src/net/cluster.rs
  src/net/endpoint.rs
  src/net/endpoint/locality.rs
Labels: size/l

#778 Update Unreal Engine Plugin
  docs/src/sdks/unreal-engine.md
  sdks/ue4/Source/Quilkin/Private/QuilkinPacketHandler.h
  sdks/ue4/Source/Quilkin/Private/QuilkinSocketSubsystem.cpp
  sdks/ue4/Source/Quilkin/Private/QuilkinSocketSubsystem.h
  sdks/ue5/.gitignore
  sdks/ue5/Quilkin.uplugin
  sdks/ue5/README.md
  sdks/ue5/Source/Quilkin/Private/QuilkinCircularBuffer.h
  sdks/ue5/Source/Quilkin/Private/QuilkinConcurrentMap.h
  sdks/ue5/Source/Quilkin/Private/QuilkinConstants.h
  sdks/ue5/Source/Quilkin/Private/QuilkinControlMessageProtocol.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinControlMessageProtocol.h
  sdks/ue5/Source/Quilkin/Private/QuilkinDelegates.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinEndpoint.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinInternetAddrs.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinInternetAddrs.h
  sdks/ue5/Source/Quilkin/Private/QuilkinLog.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinLog.h
  sdks/ue5/Source/Quilkin/Private/QuilkinModule.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinModule.h
  sdks/ue5/Source/Quilkin/Private/QuilkinPacketHandler.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinPacketHandler.h
  sdks/ue5/Source/Quilkin/Private/QuilkinResult.h
  sdks/ue5/Source/Quilkin/Private/QuilkinSettings.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinSocket.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinSocket.h
  sdks/ue5/Source/Quilkin/Private/QuilkinSocketSubsystem.cpp
  sdks/ue5/Source/Quilkin/Private/QuilkinSocketSubsystem.h
  sdks/ue5/Source/Quilkin/Private/Tests/QuilkinControlMessageProtocolTest.cpp
  sdks/ue5/Source/Quilkin/Public/QuilkinDelegates.h
  sdks/ue5/Source/Quilkin/Public/QuilkinEndpoint.h
  sdks/ue5/Source/Quilkin/Public/QuilkinSettings.h
  sdks/ue5/Source/Quilkin/Quilkin.build.cs
Labels: size/xl

#894 Remove agent note
  docs/src/services/agent.md
Labels: size/xs

#895 Update CODEOWNERS
  CODEOWNERS
Labels: size/xs
