Repository EmbarkStudios/quilkin, pull requests merged in 2024-05, with the labels that each got.

#937 Upgrade Agones CRD
  agones/src/lib.rs
  agones/src/sidecar.rs
  src/config/providers/k8s/agones.rs
Labels: size/xs

#934 Add node address selection via type and ip kind
  src/cli/agent.rs
  src/components/agent.rs
  src/components/manage.rs
  src/config.rs
  src/config/providers.rs
  src/config/providers/k8s.rs
  src/config/providers/k8s/agones.rs
  src/config/watch/agones.rs
  test/src/lib.rs
Labels: size/m

#940 Add PortPolicy::None
  src/config/providers/k8s/agones.rs
Labels: size/xs

#941 Update kube to 0.91
  Cargo.lock
  Cargo.toml
  test/src/lib.rs
  test/tests/proxy.rs
Labels: size/l

#943 Add kube@0.91 to skip-tree
  deny.toml
Labels: size/xs

#944 Add some performance optimizations
  Cargo.toml
  benches/cluster_map.rs
  benches/misc.rs
  benches/shared.rs
  proto-gen/gen.rs
  proto/quilkin/config/v1alpha1/config.proto
  src/config.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress/config.rs
  src/generated/quilkin/config/v1alpha1.rs
  src/lib.rs
  src/net/cluster.rs
  src/net/endpoint.rs
  src/net/xds.rs
  src/net/xds/resource.rs
  src/net/xds/server.rs
Labels: size/xl

#945 Upgrade Agones to 1.40.0 + CRD changes
  agones/README.md
  agones/main.tf
  agones/src/relay.rs
  docs/src/deployment/quickstarts/agones-xonotic-relay.md
  docs/src/deployment/quickstarts/agones-xonotic-xds.md
  src/config/providers/k8s/agones.rs
Labels: kind/feature, area/tests, size/s

#946 Remove idle request interval for agent
  src/cli.rs
  src/cli/agent.rs
  src/components/admin.rs
  src/components/agent.rs
  src/components/manage.rs
  src/net/xds/client.rs
Labels: size/s

#947 Remove manual build of rust-linux-darwin-builder
  build/darwin-builder/Makefile
  build/darwin-builder/cloudbuild.yaml
  build/darwin-builder/setup.sh
Labels: kind/cleanup, area/build-tools, size/m

#948 Add an optimized token router filter
  Cargo.toml
  benches/cluster_map.rs
  benches/misc.rs
  benches/shared.rs
  benches/token_router.rs
  src/components/proxy/packet_router.rs
  src/filters/chain.rs
  src/filters/compress/proto.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/load_balancer/proto.rs
  src/filters/local_rate_limit/proto.rs
  src/filters/read.rs
  src/filters/token_router.rs
  src/filters/token_router/proto.rs
  src/net/cluster.rs
  src/net/endpoint.rs
Labels: size/l

#950 Add test for hashed token router
  src/filters.rs
  src/filters/set.rs
  tests/hashed_token_router.rs
Labels: size/m

#956 Fix infinite loop
  docs/src/services/proxy/filters/writing_custom_filters.md
  src/cli.rs
  src/codec/qcmp.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
  src/net.rs
Labels: size/m

#957 Ignore config maps for agents
  src/components/agent.rs
  src/components/manage.rs
  src/components/relay.rs
  src/config/providers.rs
  src/config/watch/agones.rs
Labels: size/m

#961 Move related crates into crates directory
  Cargo.toml
  build/Makefile
  crates/agones/.gitignore
  crates/agones/Cargo.toml
  crates/agones/README.md
  crates/agones/helm.yaml
  crates/agones/main.tf
  crates/agones/src/lib.rs
  crates/agones/src/pod.rs
  crates/agones/src/provider.rs
  crates/agones/src/relay.rs
  crates/agones/src/sidecar.rs
  crates/macros/Cargo.toml
  crates/macros/README.md
  crates/macros/src/include.rs
  crates/macros/src/lib.rs
  crates/proto-gen/Cargo.toml
  crates/proto-gen/gen.rs
  crates/test/Cargo.toml
  crates/test/src/lib.rs
  crates/test/tests/mesh.rs
  crates/test/tests/proxy.rs
Labels: size/s

#962 Always build token maps
  crates/test/tests/mesh.rs
  src/net/cluster.rs
  src/net/xds.rs
Labels: size/s

#965 Nuke non-delta streams
  Cargo.lock
  crates/xds/src/client.rs
  crates/xds/src/metrics.rs
  crates/xds/src/server.rs
  docs/src/deployment/quickstarts/netcat.md
  src/components/agent.rs
  src/components/manage.rs
  src/components/proxy.rs
Labels: size/l

#966 Fix relay listener updates
  crates/test/src/lib.rs
  crates/test/tests/mesh.rs
  crates/test/tests/proxy.rs
  crates/xds/src/client.rs
  crates/xds/src/config.rs
  crates/xds/src/lib.rs
  crates/xds/src/resource.rs
  crates/xds/src/server.rs
  src/cli/proxy.rs
  src/components/manage.rs
  src/components/proxy.rs
  src/components/relay.rs
  src/config.rs
  src/config/slot.rs
  src/config/watch/fs.rs
  src/filters.rs
  src/test.rs
Labels: size/l

#968 Move MaxmindDb::lookup to session creation
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
Labels: size/s

#969 Increase downstream->upstream buffer
  src/components/proxy/sessions.rs
Labels: size/xs
