Repository EmbarkStudios/quilkin, pull requests merged in 2024-06, with the labels that each got.

#971 Guide: Show command options for `manage providers`
  docs/preprocessor.sh
  docs/src/services/xds/providers/agones.md
  docs/src/services/xds/providers/filesystem.md
Labels: kind/documentation, kind/cleanup, size/s

#972 Github: PR Labeler action
  .github/pull_request_template.md
  .github/workflows/label-pr.yml
Labels: kind/cleanup, area/build-tools, size/s

#974 Build tooling updates and fixes.
  build/Makefile
  build/README.md
  build/build-image/Dockerfile
  rust-toolchain.toml
  src/filters/registry.rs
  src/net/phoenix.rs
Labels: kind/cleanup, size/s

#977 Update crates
  Cargo.lock
  Cargo.toml
  deny.toml
  src/components/admin.rs
  src/components/admin/health.rs
  src/net/endpoint/address.rs
  src/net/maxmind_db.rs
  src/net/phoenix.rs
  tests/health.rs
  tests/metrics.rs
Labels: size/l, kind/other

#978 Build single token -> address map
  src/filters/token_router.rs
  src/net/cluster.rs
Labels: size/m, kind/other

#979 Cleanup
  .github/workflows/ci.yml
  crates/xds/Cargo.toml
  crates/xds/src/client.rs
  crates/xds/src/config.rs
  crates/xds/src/lib.rs
  crates/xds/src/locality.rs
  crates/xds/src/resource.rs
  crates/xds/src/server.rs
Labels: size/m, kind/other

#980 Rename HashedTokenRouter -> TokenRouter
  benches/token_router.rs
  crates/test/tests/mesh.rs
  src/filters.rs
  src/filters/set.rs
  src/filters/token_router.rs
  src/net/cluster.rs
  tests/hashed_token_router.rs
Labels: size/m, kind/other
