Repository EmbarkStudios/quilkin, pull requests merged in 2025-02, with the labels that each got.

#1084 Add QCMP support in XDP I/O loop
  crates/ebpf/Cargo.lock
  crates/ebpf/Cargo.toml
  crates/ebpf/src/ebpf-main.rs
  crates/test/tests/xdp.rs
  crates/xdp/bin/packet-router.bin
  crates/xdp/src/lib.rs
  src/cli/service.rs
  src/net/xdp.rs
  src/net/xdp/process.rs
  src/time.rs
Labels: size/m, kind/other

#1087 feat: Add xDS provider
  src/config/providersv2.rs
Labels: size/s, kind/other

#1086 Nuke compression filter
  Cargo.lock
  Cargo.toml
  benches/compression.rs
  benches/misc.rs
  crates/proto-gen/gen.rs
  crates/quilkin-proto/src/generated/quilkin/filters.rs
  crates/quilkin-proto/src/generated/quilkin/filters/compress.rs
  crates/quilkin-proto/src/generated/quilkin/filters/compress/v1alpha1.rs
  docs/src/SUMMARY.md
  docs/src/deployment/quickstarts/agones-xonotic-sidecar.md
  docs/src/services/proxy/filters.md
  docs/src/services/proxy/filters/compress.md
  docs/src/services/xds/proto/index.md
  proto/quilkin/filters/compress/v1alpha1/compress.proto
  src/collections/pool.rs
  src/components/proxy/packet_router.rs
  src/filters.rs
  src/filters/compress.rs
  src/filters/compress/compressor.rs
  src/filters/compress/config.rs
  src/filters/compress/metrics.rs
  src/filters/error.rs
  src/filters/set.rs
  src/lib.rs
  src/net/xdp/process.rs
  tests/compress.rs
  tests/filter_order.rs
Labels: size/xl, kind/other

#1089 Add TLS options
  Cargo.lock
  Cargo.toml
  crates/xds/src/server.rs
  src/cli/service.rs
Labels: size/m, kind/other

#1090 Add check that clap arguments are valid
  .github/workflows/ci.yml
  src/cli/service.rs
Labels: size/s, kind/other

#1092 Remove some actions
  .github/workflows/labeler.yml
  .github/workflows/pr_update.yml
Labels: size/s, kind/other

#1091 fix: use new health check bool
  src/cli.rs
  src/components/admin.rs
  src/config/providersv2.rs
  src/main.rs
  src/test.rs
Labels: size/m, kind/other

#1095 Fixup QCMP ping
  .ci/xdp/veth-integ-test.sh
  crates/ebpf/Cargo.toml
  crates/ebpf/build.sh
  crates/ebpf/src/dummy.c
  crates/xdp/bin/dummy.bin
  crates/xdp/src/lib.rs
  src/cli.rs
  src/cli/proxy.rs
  src/cli/qcmp.rs
  src/cli/service.rs
  src/components/proxy.rs
Labels: kind/other

#1096 Allow service initialization to fail
  src/cli/service.rs
Labels: kind/other

#1098 Remove datacenters from phoenix
  src/config.rs
  src/net/phoenix.rs
Labels: kind/other

#1097 feat: Add service.id as a parameter
  src/cli/service.rs
  src/config.rs
Labels: kind/other

#1099 Update crates
  Cargo.lock
  Cargo.toml
  benches/shared.rs
  benches/token_router.rs
  crates/test/tests/mesh.rs
  crates/xds/src/client.rs
  deny.toml
  src/filters/load_balancer/endpoint_chooser.rs
  src/net/endpoint/address.rs
  src/net/phoenix.rs
Labels: kind/other

#1102 Cleanup docs CI
  build/Makefile
  docs/htmltest.yaml
Labels: kind/other

#1104 chore: Allow XDS provider to be enabled with just specifying endpoints
  src/config/providersv2.rs
Labels: kind/other

#1103 chore: share only incrementing errors if not a filter packet drops between XDP and io-uring
  src/components/proxy/error.rs
  src/components/proxy/packet_router.rs
  src/net/xdp/process.rs
Labels: kind/other

#1105 Add session metrics to XDP
  crates/test/tests/xdp.rs
  src/components/proxy.rs
  src/components/proxy/sessions/inner_metrics.rs
  src/metrics.rs
  src/net/maxmind_db.rs
  src/net/xdp.rs
  src/net/xdp/process.rs
Labels: kind/other

#1111 Update crates
  Cargo.lock
  Cargo.toml
Labels: kind/other

#1108 Defer shutdown until actives sessions are 0
  .github/workflows/ci.yml
  build/build-image/Dockerfile
  cloudbuild.yaml
  src/cli.rs
  src/cli/proxy.rs
  src/cli/service.rs
  src/components/proxy.rs
  src/components/proxy/sessions.rs
  src/net/io_uring.rs
  src/net/packet/queue.rs
  src/net/phoenix.rs
Labels: kind/other

#1113 Fully refresh local state on new connection
  crates/xds/src/client.rs
  crates/xds/src/config.rs
Labels: kind/other

#1114 Use XDP wakeup
  Cargo.lock
  crates/test/tests/xdp.rs
  crates/xdp/Cargo.toml
  crates/xdp/src/lib.rs
  src/net/xdp.rs
Labels: kind/other

#1115 feat: Add phoenix_distance metric
  src/metrics.rs
  src/net/packet/queue.rs
  src/net/phoenix.rs
Labels: kind/other

#1119 Update xdp and print out device caps after query
  Cargo.lock
  crates/xdp/Cargo.toml
  src/net/xdp.rs
Labels: kind/other

#1121 chore: Remove parts of GCB that are covered by GHA
  build/Makefile
  build/build-image/Dockerfile
  cloudbuild.yaml
Labels: kind/other

#1120 chore: Add source label to QCMP errors
  src/codec/qcmp.rs
Labels: kind/other

#1123 Begin config migration
  Cargo.lock
  Cargo.toml
  crates/test/src/lib.rs
  src/cli.rs
  src/cli/agent.rs
  src/cli/proxy.rs
  src/cli/service.rs
  src/components/admin.rs
  src/components/agent.rs
  src/components/manage.rs
  src/components/proxy.rs
  src/config.rs
  src/config/providers/k8s.rs
  src/config/providersv2.rs
  src/config/serialization.rs
  src/config/watch/agones.rs
  src/config/watch/fs.rs
  src/metrics.rs
  src/net/phoenix.rs
Labels: kind/other

#1124 Make Config::filters a dynamic property
  crates/test/src/lib.rs
  crates/test/tests/xdp.rs
  src/cli/service.rs
  src/components/proxy.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
  src/config.rs
  src/config/providers.rs
  src/config/providersv2.rs
  src/config/serialization.rs
  src/config/watch/agones.rs
  src/net/xdp.rs
  src/net/xdp/process.rs
  tests/capture.rs
  tests/concatenate.rs
  tests/filter_order.rs
  tests/filters.rs
  tests/firewall.rs
  tests/load_balancer.rs
  tests/local_rate_limit.rs
  tests/match.rs
  tests/token_router.rs
Labels: kind/other

#1128 Move datacenters/agent to typemap
  crates/test/tests/mesh.rs
  src/cli/service.rs
  src/components/agent.rs
  src/config.rs
  src/config/serialization.rs
Labels: kind/other

#1132 feat: parse origin IP through proxy headers
  Cargo.lock
  crates/xds/Cargo.toml
  crates/xds/src/config.rs
  crates/xds/src/server.rs
  src/config.rs
Labels: kind/other

#1135 Ignore normal errors
  src/net/xdp.rs
  src/net/xdp/process.rs
Labels: kind/other

#1138 Update to xdp 0.5.0
  Cargo.lock
  Cargo.toml
  crates/test/Cargo.toml
  crates/test/tests/snapshots/xdp__simple_forwarding.snap
  crates/test/tests/xdp.rs
  crates/xdp/Cargo.toml
  src/net/xdp/process.rs
Labels: kind/other

#1142 fix: set distance metric on none branch
  src/net/phoenix.rs
Labels: kind/other

#1144 fix: shutdown on panic
  src/cli.rs
  src/components/admin.rs
  src/components/admin/health.rs
  src/signal.rs
  src/test.rs
Labels: kind/other
