Repository EmbarkStudios/quilkin, pull requests merged in 2025-01, with the labels that each got.

#1054 Make filters generic over the packet buffer
  .github/workflows/ci.yml
  benches/compression.rs
  benches/token_router.rs
  build/build-image/Dockerfile
  cloudbuild.yaml
  src/components/proxy/packet_router.rs
  src/config/slot.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/capture/affix.rs
  src/filters/capture/regex.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/compress/compressor.rs
  src/filters/concatenate.rs
  src/filters/debug.rs
  src/filters/drop.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/load_balancer/endpoint_chooser.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/pass.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/filters/write.rs
  src/pool.rs
  src/test.rs
Labels: size/l, kind/other

#1056 refactor: Make DownstreamPacket sans-io
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/reference.rs
  src/components/proxy/sessions.rs
  src/config/slot.rs
  src/filters.rs
  src/filters/capture.rs
  src/filters/chain.rs
  src/filters/compress.rs
  src/filters/compress/compressor.rs
  src/filters/concatenate.rs
  src/filters/debug.rs
  src/filters/drop.rs
  src/filters/firewall.rs
  src/filters/load_balancer.rs
  src/filters/local_rate_limit.rs
  src/filters/match.rs
  src/filters/pass.rs
  src/filters/read.rs
  src/filters/registry.rs
  src/filters/timestamp.rs
  src/filters/token_router.rs
  src/filters/write.rs
  src/pool.rs
  src/test.rs
Labels: size/m, kind/other

#1057 refactor: Move pool into collections module
  benches/compression.rs
  benches/token_router.rs
  crates/test/src/lib.rs
  src/collections.rs
  src/collections/pool.rs
  src/components/proxy.rs
  src/components/proxy/io_uring_shared.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/sessions.rs
  src/filters/token_router.rs
  src/lib.rs
  src/test.rs
Labels: size/s, kind/other

#1058 refactor: Rename PendingSends to PacketQueue, move PacketQueue and io-uring to net module
  crates/test/src/lib.rs
  crates/test/tests/proxy.rs
  src/cli/proxy.rs
  src/components/proxy.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/io_uring.rs
  src/components/proxy/packet_router/reference.rs
  src/components/proxy/sessions.rs
  src/components/proxy/sessions/io_uring.rs
  src/components/proxy/sessions/reference.rs
  src/net.rs
  src/net/io_uring.rs
  src/net/packet.rs
  src/net/packet/queue.rs
  src/test.rs
  tests/firewall.rs
Labels: size/m, kind/other

#1059 feat: Add initial nmap-service-probes crate
  Cargo.lock
  Cargo.toml
  crates/nmap-service-probes/Cargo.toml
  crates/nmap-service-probes/README.md
  crates/nmap-service-probes/src/lib.rs
  crates/nmap-service-probes/src/parser.rs
  crates/nmap-service-probes/src/parser/hex.rs
Labels: size/xl, kind/other

#1061 chore: make phoenix server errors debug logs
  src/net/phoenix.rs
Labels: size/xs, kind/other

#1060 refactor: Remove pipeline logging
  crates/test/tests/proxy.rs
  src/components/proxy.rs
  src/components/proxy/error.rs
  src/components/proxy/packet_router.rs
  src/components/proxy/packet_router/io_uring.rs
  src/components/proxy/packet_router/reference.rs
  src/net/io_uring.rs
Labels: size/m, kind/other

#1063 refactor: Move admin CLI options under prefix, add better top-line help text
  src/cli.rs
Labels: size/s, kind/other

#1064 refactor: Move locality arguments to top-level
  crates/test/tests/proxy.rs
  src/cli.rs
  src/cli/agent.rs
  src/cli/manage.rs
  tests/qcmp.rs
Labels: size/s, kind/other

#1066 First pass implementation of XDP I/O loop
  Cargo.lock
  Cargo.toml
  crates/test/Cargo.toml
  crates/test/tests/snapshots/xdp__changes_ip_version-2.snap
  crates/test/tests/snapshots/xdp__changes_ip_version.snap
  crates/test/tests/snapshots/xdp__simple_forwarding.snap
  crates/test/tests/xdp.rs
  crates/xdp/Cargo.toml
  crates/xdp/src/lib.rs
  deny.toml
  src/collections/ttl.rs
  src/filters/concatenate/config.rs
  src/net.rs
  src/net/xdp.rs
  src/net/xdp/process.rs
Labels: size/xl, kind/other

#1069 Add XDP CLI options and initialization code
  Cargo.lock
  crates/test/src/lib.rs
  crates/xdp/src/lib.rs
  src/cli/proxy.rs
  src/components/proxy.rs
  src/net/xdp.rs
  src/test.rs
Labels: size/m, kind/other

#1070 feat: Allow XDP when force flag is set
  src/components/proxy.rs
Labels: size/xs, kind/other

#1073 Update xdp to 0.1.0
  Cargo.lock
  crates/test/tests/xdp.rs
  crates/xdp/Cargo.toml
  src/net/xdp/process.rs
Labels: size/s, kind/other

#1077 Fix umem leak
  crates/test/tests/xdp.rs
  src/net/xdp/process.rs
Labels: size/m, kind/other

#1079 chore: Refactor tracing and shutdown signals into their own functions
  benches/shared.rs
  crates/test/src/lib.rs
  src/alloc/metrics.rs
  src/cli.rs
  src/cli/agent.rs
  src/cli/manage.rs
  src/cli/proxy.rs
  src/cli/relay.rs
  src/cli/service.rs
  src/codec/qcmp.rs
  src/components.rs
  src/components/proxy.rs
  src/lib.rs
  src/net/phoenix.rs
  src/signal.rs
  src/test.rs
  tests/qcmp.rs
Labels: size/m, kind/other

#1080 refactor: Add new providers struct, and use it for agents
  src/components/agent.rs
  src/config.rs
  src/config/providersv2.rs
  src/config/watch/agones.rs
Labels: size/m, kind/other

#1081 refactor: Move Relay & Manage to use config providers.
  crates/test/src/lib.rs
  src/cli.rs
  src/cli/relay.rs
  src/components/manage.rs
  src/components/relay.rs
Labels: size/m, kind/other

#1078 Add XDP integration test
  .ci/xdp/cluster-config.yaml
  .ci/xdp/integration-test.sh
  .ci/xdp/proxy.dockerfile
  .ci/xdp/proxy.dockerfile.dockerignore
  .ci/xdp/server.yaml
  .ci/xdp/spinup-cluster-with-registry.sh
  .ci/xdp/veth-integ-test.sh
  .github/workflows/xdp-integration-test.yml
  .gitignore
Labels: size/m, kind/other

#1082 chore: Add static provider, allow XDP option be set through env, allow no command in CLI
  src/cli.rs
  src/cli/service.rs
  src/config/providersv2.rs
Labels: size/m, kind/other

#1085 fix: fix env var names
  src/cli/service.rs
Labels: size/s, kind/other
